go-vela/server

- api/webhook.go
- database/init_cgo.go
- database/service_test.go
- secret/vault/list_test.go
- source/github/repo_test.go
- util/util.go
https://goreportcard.com/report/github.com/go-vela/server
> Refactor to improve Go Report Card

- api/build.go
- database/build.go
- database/build_test.go
- database/database.go
- database/dml/dml_test.go
- database/dml/postgres/build.go
- database/dml/postgres/build_test.go
- database/dml/postgres/postgres_test.go
- database/dml/postgres_test.go
- database/dml/sqlite/build.go
- database/dml/sqlite/build_test.go
- database/dml/sqlite/sqlite_test.go
- database/dml/sqlite_test.go
adds the ability to query the builds endpoint with an optional query parameter to filter results by event type (pull, push, tag, deploy)
> feat(event): add ability to filter builds by events

- api/repo.go
- database/repo_test.go
- go.mod
- go.sum
- router/middleware/build/build_test.go
- router/middleware/perm/perm.go
- router/middleware/perm/perm_test.go
- router/middleware/repo/repo_test.go
- router/middleware/service/service_test.go
- router/middleware/step/step_test.go
Part of the work effort for:
go-vela/server#87
> feat: enable public access to builds/repos

- api/secret.go
defaults are handled client-side causing inconsistent experience across touch points. this change will put that responsibility in one place.
> enhancement(secrets): add default events for secrets

- queue/redis/redis.go
Helps the administrator validate the reason the connection failure is occurring.
> refactor(redis): return actual error upon connection failure

- api/webhook.go
- database/build_test.go
- database/ddl/postgres/build.go
- database/ddl/sqlite/build.go
- go.mod
- go.sum
- router/middleware/build/build_test.go
- source/github/repo.go
- source/github/repo_test.go
- source/github/webhook.go
- source/github/webhook_test.go
- source/source.go
Continues the work from https://github.com/go-vela/types/pull/85.
> feat(build): add headref for pull requests

- api-spec/vela-server.json
- api/authenticate.go
- api/login.go
This reorganizes the swagger spec for /login and /authenticate endpoints. No code changes.
> fix(open-api): Reorganize the login/authenticate swagger definitions

- secret/native/crypto.go
This fix is to improve the experience when an admin needs to modify secrets. Sending encryted data over HTTP when it's not encoding is unsafe because it does not follow the UTF-8 standard. 
When the data does get sent some contents within the value field to not get marshaled properly which means the secret becomes invalid. This fix adds a simple base64 encode/decode process to ensure the character set is compatible with all interactions of the secrets. 
fixes: https://github.com/go-vela/community/issues/100
> fix: add encoding component

- api/logout.go
- router/router.go
pretty simple change to make logout actually work. it was not getting the user previously 😿
> fix(logout): make logout work properly

- api/repo.go
- cmd/vela-server/main.go
- cmd/vela-server/server.go
- router/middleware/default_timeout.go
- router/middleware/default_timeout_test.go
closes https://github.com/go-vela/community/issues/179
> enhance(repo): let server override default build timeout

- api/login.go
> fix: remove log

- cmd/vela-server/main.go
- go.mod
- go.sum
This adds support for `.env` files to the Vela server application.
> enhance: support .env files

- api/build_test.go
- database/postgres/build_test.go
- database/postgres/hook_test.go
- database/postgres/repo_test.go
- database/postgres/service_test.go
- database/postgres/step_test.go
- go.mod
- go.sum
- source/github/deployment.go
- source/github/deployment_test.go
- source/github/testdata/deployments.json
Add payload to getters for deployment endpoints.
> fix(deployments): add deployment payload to getters

- api/build.go
- api/webhook.go
closes [#385](https://github.com/go-vela/community/issues/385)
I didn't see any related tests for this file, so I haven't added any. Let me know if I missed them 👀
> fix: report status on skip

- source/github/opts.go
- source/github/opts_test.go
Addressing issue go-vela/community#335
> Fix for issue go-vela/community#335

- api/repo.go
document addition introduced in https://github.com/go-vela/server/pull/506
> docs(api): document active filter

- api/secret.go
Fixing a bug that was merged into `v0.12.1` in https://github.com/go-vela/server/pull/590
PR to master here: https://github.com/go-vela/server/pull/598
> fixing whitespace secret bug

- .github/workflows/build.yml
- .github/workflows/prerelease.yml
- .github/workflows/publish.yml
- .github/workflows/reviewdog.yml
- .github/workflows/spec.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
same as https://github.com/go-vela/types/pull/270
> fix(actions): make sure to use latest Go version

- go.mod
- go.sum
just trying to limit the blast radius, this got snuck in from development.
> fix: revert buildkite yaml upgrade from #765

- cmd/vela-server/validate.go
> fix(validate): update validation to use new, shorter name for token durations

- database/build/opts_test.go
forgot to add this test in #922
> chore: add WithContext test to builds

- api/build/restart.go
Preparing patch release of `v0.20.2`. Will include these changes: https://github.com/go-vela/server/pull/958
> patch(api/build): add commit to compiler instantiation

- .github/workflows/validate-pr-title.yml
See https://github.com/go-vela/types/pull/344
> enhance(ci): add PR title validation

- api/build/restart.go
- api/deployment/get.go
- api/webhook/post.go
- database/deployment/delete.go
- database/deployment/delete_test.go
- database/deployment/get.go
- database/deployment/get_test.go
- database/deployment/interface.go
- database/deployment/update.go
- database/deployment/update_test.go
- database/integration_test.go
see: https://github.com/go-vela/community/issues/832
> chore: add context to deployment functions

- database/deployment/table.go
- go.mod
- go.sum
Now `500`. See https://github.com/go-vela/types/pull/355
> fix(database): increase build character count in deploy table

- api/build/approve.go
Make sure the approver is not the owner of the repo.
Also make sure the approver is not the sender of the build, as that would be counter-intuitive to the fact that we have a `no-write` option in place.
> fix(build-approval): correct approved_by and disallow self-approval

- database/types/dashboard.go
See https://pkg.go.dev/github.com/google/uuid@v1.6.0#NewV7 for rationale on why we should upgrade here
> fix(dashboards): use v7 uuid for primary key

- api/types/events.go
- api/types/events_test.go
- compiler/native/compile_test.go
- go.mod
- go.sum
[This change](https://github.com/go-vela/server/pull/1087) enforces the `action` part of this function, so we need to check for that
> fix(events): add action to deployment check

- api/dashboard/delete.go
- api/dashboard/get.go
404 can occur via dashboard middleware
> fix(api-spec): add missing 404 responses in docs

- api/types/settings/compiler.go
- api/types/settings/platform.go
- api/types/settings/queue.go
forgot to add yaml tags, necessary for updating from yaml file in the cli
> fix: platform settings yaml tags

- api/admin/settings.go
> fix(settings): swagger missing 401 responses

- api/log/get_service.go
- api/log/get_step.go
instead of returning an internal server error when a request asks for a log that doesn't exist, return a 404. this should set up more nicely when there is a log pruning process in place that results in logs not being available anymore, so a UI can deal with the scenario more easily, for example.
probably should extend to some other endpoints as well.
> fix(api): return 404 when log doesn't exist

- tracing/flags.go
figured the wording could be more clear.
> chore(tracing): better flag description wording

- compiler/template/native/render_test.go
- compiler/template/native/testdata/step/bad_ruleset_format.yml
- compiler/template/native/testdata/step/basic/step.yml
- compiler/types/yaml/yaml/ruleset.go
- compiler/types/yaml/yaml/ruleset_test.go
- compiler/types/yaml/yaml/testdata/ruleset_collide.yml
- compiler/types/yaml/yaml/testdata/ruleset_collide_adv.yml
- compiler/types/yaml/yaml/testdata/ruleset_unknown_field.yml
Bringing back https://github.com/go-vela/server/pull/1256 which was reverted due to breaking some user pipelines. Probably best reserved for a minor release instead of a patch.
> enhance(compiler)!: return rules unmarshal errors

- compiler/native/compile.go
- compiler/types/pipeline/container.go
- compiler/types/pipeline/ruleset.go
- compiler/types/pipeline/ruleset_test.go
- compiler/types/pipeline/secret.go
- compiler/types/pipeline/stage.go
- compiler/types/yaml/yaml/ruleset.go
- docker-compose.yml
- go.mod
- go.sum
xref: https://github.com/go-vela/community/pull/1026
> feat(ruleset): add eval logic

- .github/workflows/test.yml
see https://github.com/codecov/codecov-action?tab=readme-ov-file#using-oidc
> chore(ci): use oidc for codecov

- compiler/native/compile.go
- compiler/native/compile_test.go
- compiler/native/testdata/inline_with_stages.yml
- compiler/types/yaml/yaml/service.go
Users who have specified rulesets for services will now see them honored 😅 
CompileLite will honor service and secret origin rulesets
> fix(compiler)!: rectify service and secret rulesets for Compile and CompileLite

- api/build/restart.go
- api/webhook/post.go
Applying https://github.com/go-vela/server/pull/1313 to `v0.26.5` patch branch
> fix(patch-v0.26.5): apply gatekeep build obj bug fix
