api/user.go
For the UI to work with Favorites, we need to let the user see repos that have already been activated.
This way, they can add those repos to their favorites from the Add Repos page based on the Source Repos they have access to, even if someone else has already activated it.
=> fix(source_repos): reverting source repos 'already-active' filter

api/webhook.go
I previously had attempted to fix this bug by duplicating the `gin.Context`:
https://github.com/go-vela/server/pull/98
Unfortunately, this didn't resolve the bug because the `http.Request` in that duplicated context always had an empty body.
To resolve this, we're now going to clone the request in the `gin.Context`, and pass that along to [where we call the VerifyWebhook()](https://github.com/go-vela/server/blob/eb0e218542c96fce173f834595457b6cfe0efa12/api/webhook.go#L110-L119) function.
Context:
I can't say with 100% certainty that this change is the golden fix, but it is at least still better.
I verified that we're now seeing the `http.Request` we pass to the [VerifyWebhook()](https://github.com/go-vela/server/blob/eb0e218542c96fce173f834595457b6cfe0efa12/source/github/webhook.go#L60-L69 …
=> fix: duplicate http.Request for webhook validation

api/secret.go
example: current implementation does not allow `[ "library/node" ]` to be updated to `[]`
=> fix(secrets): allow secret images to be set to none

source/github/webhook.go
This PR is based off of https://github.com/go-vela/compiler/pull/54 👍 
The thought is that `TrimPrefix()` is easier to read and understand what the code is doing.
Also, it's a more proper fit for the functionality we're trying to accomplish.
Thanks @wass3r 🎉
=> refactor(source): use TrimPrefix() over Replace()

api/authenticate.go
i don't believe uuid can produce something with spaces? also, to stay consistent with https://github.com/go-vela/server/blob/master/api/user.go#L416
=> refactor: remove trimspace

go.mod, go.sum
This pulls in the latest `go-vela/compiler` code that can support YAML for Deployments 👍
=> feat: support deployment target

api/repo.go, source/github/repo.go, source/github/repo_test.go, source/github/testdata/hooks_multi.json
there are various scenarios where repositories might end up with multiple hooks for the same vela installation. this change will correct issues when trying to disable or repair repos with this scenario.
also sets the repo to active after a successful repair operation.
=> fix(hooks): account for multiple hooks in repo disable

source/github/repo.go, source/github/repo_test.go
closes https://github.com/go-vela/community/issues/67
GitHub has a completely different endpoint for setting a status for a deployment:
https://developer.github.com/v3/repos/deployments/#create-a-deployment-status
In order to use this endpoint, we need to know the deployment ID we're dealing with thats tracked in the `build.Source` field 👍 
This PR adds the functionality to capture the deployment ID from the `build.Source` field.
Using that information, we're then able to create a status on the deployment so they're no longer marked as "abandoned".
Also contained in this PR is a new test to ensure the code written works 😄
=> feat(source): set build status for deployments

database/ddl/postgres/user.go
This PR updates the size of the `favorites` column in the `users` table to `5000`.
It previously was `1000` which allowed for ~ 30 repos to be favorited depending on the size of the repo names.
As an example, a user/team who favorites repos that are named like this:
* superCrazyLongOrgName/superCrazyLongRepoName
are going to fill up that `favorites` column a lot faster than a user/team who favorites repos that are named like this:
* shortOrg/shortRepo
=> fix(postgres): update favorites column in user table to 5000

api/webhook.go, go.mod, go.sum
closes https://github.com/go-vela/community/issues/66 and closes https://github.com/go-vela/community/issues/70
companion PR to https://github.com/go-vela/types/pull/86
- uses new method on hook to determine whether the hook should be skipped
- returns 200 and reason for skip
note: will update PR and remove replace directive in `.mod` once PR in _types_ is in. actions pipeline will show errors for now.
=> feat(skip): add check to determine if hook should be skipped

api/secret.go, secret/vault/vault.go, secret/vault/vault_test.go
The current implementation will incorrectly update the `AllowCommand` to be `true` even if the user supplies `false`. For example: 
```
vela add secret --secret.engine vault --secret.type repo --org JordanSussman --repo vela-local-test --name test --value bar --event comment --event deployment --event pull_request --event push --event tag --commands=false
{
AllowCommand: true,
Events: [comment deployment pull_request push tag],
ID: 0,
Images: [],
Name: test,
Org: JordanSussman,
Repo: vela-local-test,
Team: ,
Type: repo,
Value: [secure],
}
```
=> fix(secrets): properly set default value for allow_command

api/repo.go
See https://github.com/go-vela/cli/pull/163 for more information.
This PR updates the `active` flag to have a default value of `true` **only** if it hasn't been provided in the request body 👍
=> fix(api): setting active flag for repo

api/build.go
fixes https://github.com/go-vela/community/issues/116
we have applied a similar fix in https://github.com/go-vela/server/pull/166 and missed a couple of instances. applied it in `RestartBuild` and then also noticed it in `CreateBuild`.
=> fix(build): restart on build without changeset

api/build.go, api/webhook.go
Currently, there is a pesky bug that our users experience when Vela processes a webhook:
```sql
unable to create new build for <org>/<repo>: pq: duplicate key value violates unique constraint "builds_repo_id_number_key"
```
This error is displayed when we attempt to create a build in the database that contains the same build `number` and `repo_id`.
This attempts to resolve that issue by creating a retry loop with backoff that will repeat the following operations:
* capture the last build for the repo
* set fields on the new build object to be created in the database
* compile the pipeline with the new build object
* create the pipeline objects (i.e. build, services, steps) in the database
The source of the error message can be found in our webhook workflow, where at the very end we call …
=> fix: webhook race condition on build creation

api/webhook.go
More context and information can be found with https://github.com/go-vela/server/pull/186
This is intended to fix a few consequential side effects from the previous change (above linked PR):
* decrease the retry limit from `5` to `3`
* skip retrying the compilation of the pipeline on failures
* add extra error handling after creating the build in the database
More information on each change is described below 👍 
Currently, the webhook process has a retry loop that has a limit of `5` and incrementally sleeps between each iteration.
However, the amount of time spent sleeping between the iterations grows to where it exceeds timeouts for the source provider.
As an example, GitHub currently has a timeout of ~ `10s` of waiting for a response from the webhook.
Since the retry limit is set to …
=> fix: webhook race condition on build creation v2

cmd/vela-server/validate.go
Currently, when spinning up the Vela server, an error message is thrown:
```sh
{"level":"fatal","msg":"vault auth method of '' is unsupported","time":"2020-10-09T16:07:06Z"}
```
After some digging, it appears we're always expecting the `vault-auth-method` flag to be provided, even if the user specifies a `vault-token` flag.
I believe this PR addresses the issue by only checking the `vault-auth-method` flag if no `vault-token` flag is provided.
=> fix(vault): skip auth method if token is provided

.github/workflows/prerelease.yml, .github/workflows/publish.yml, Dockerfile-alpine
Adding another `Dockerfile` based on alpine since I unfortunately need access to some image with a shell to allow me to modify the environment variables before the binary is started. My specific use case involves needing to generate the `VELA_DATABASE_CONFIG` and `VELA_QUEUE_CONFIG` environment variables utilizing others that are injected at run time.
- Add `Dockerfile-alpine` file to utilize alpine as base image instead of scratch
- Update `.github/workflows/publish.yml` to publish `latest-alpine` image
- Update `.github/workflows/prerelease.yml` to publish `${GITHUB_TAG}-latest` image
=> chore(docker): publish alpine images

.github/CONTRIBUTING.md, api/repo.go, api/webhook.go, cmd/vela-server/main.go, cmd/vela-server/server.go, docker-compose.yml, go.mod, router/middleware/webhook_validation.go, router/middleware/webhook_validation_test.go
When developing locally you currently have to comment out code in order to get the server to allow you to enable/disable repos.  This pr adds a new flag for disabling webhook validation.
`VELA_DISABLE_WEBHOOK_VALIDATION` - default: false
Changes were tested locally for both cases (with and without validation enabled)
=> enhancement: add flag for disabling webhook validation

api/repo.go
Related to https://github.com/go-vela/server/pull/200 and https://github.com/go-vela/server/pull/207
Currently, there is a bug where not all the fields provided in the JSON payload when creating a repo are respected.
This PR intends to resolve this issue by ensuring we set fields based off the input provided.
=> fix: set repo fields off input provided

api-spec/vela-server.json, api/log.go
Fix the swagger spec to return the correct type for the get build logs endpoint.
Fixes https://github.com/go-vela/community/issues/147
=> fix(api-spec): Log spec return type

api-spec/vela-server.json, api/badge.go, api/build.go, api/deployment.go, api/hook.go, api/log.go, api/repo.go, api/secret.go, api/service.go, api/step.go, api/user.go, api/worker.go
Fix swagger spec parameters
This fixes a few things with swagger spec parameters:
* Consistently put the path arguments in the same order found in the path
* Put body arguments after path arguments
* Correct the description of the Service arguments to indicate its an ID, not a name
* Fix the Workers API to use the "security" parameter, rather than header parameters
This is important to code-generation, as many of the created functions will have positional arguments, and we need them to match the API usage.
=> fix(open-api): spec parameter order correction

api/repo.go
Currently, if you disable and re-enable a repository, we don't properly update the "owner" of that repo in Vela.
This ensures that we set the proper repo owner if the event a user attempts to disable and re-enable a repository.
=> fix(api): setting repo owner for enabled repo

api/webhook.go, go.mod, go.sum
should fix https://github.com/go-vela/community/issues/181
This fix will create a clone of the `Engine` with basic settings before compiling the incoming request. This is to avoid situation where the shared compiler attached at application start up is "corrupted" with other build data.
Tested by emitting multiple concurrent requests and logging on the worker where the situation was observed prior to the fix and not after.
Testing surfaced another issue where we attach an error if the first attempt to create a build fails. When the subsequent attempt succeeds the error is not cleared.
Note: an arguably nicer solution would be to handle this via mutex. i did spend some time on that, but i think it might require some additional changes.
=> fix(webhook): duplicate compiler before processing

api/authenticate.go, source/github/authentication.go, source/github/authentication_test.go, source/source.go
small fix-up for #246 as indicated in the discussion on that story
=> fix: post-merge linter fixes

cmd/vela-server/main.go, cmd/vela-server/server.go
Based off of https://github.com/go-vela/server/pull/247
This is a partial revert of https://github.com/go-vela/server/pull/236
We will still continue to use `url.Parse()` in the codebase but will allow customizing the port the API listens on.
=> refactor: add API port back to server

go.mod, go.sum
Upgrading [go-vela/compiler](https://github.com/go-vela/compiler) on `v0.7.0-rc4`
https://github.com/go-vela/compiler/releases/tag/v0.7.0-rc4
=> chore: update go-vela/compiler on v0.7.0-rc4

source/github/deployment.go, source/github/webhook.go
Closes https://github.com/go-vela/community/issues/198
This enables Vela to properly handle a webhook for the `deployment` event with an "empty" `payload` field.
> NOTE:
>
> After discussions with Jordan Sussman, we learned that GitHub actually does support a string in the `payload` field:
>
> From GitHub Support:
> > If the payload is passed in the input when creating a deployment, this endpoint expects it to either be a JSON object or a string. Otherwise, a validation error will be thrown.
>
> However, we agreed that it is still better to adopt GitHub's default behavior of setting an empty map `{}`
>
> We believe this is a more transparent approach due to the default behavior of GitHub.
Previously, we were setting the `payload` field to an empty string (`""`) if one wasn't provided: …
=> fix(source): processing deployments with empty payloads

database/service.go, database/service_test.go, database/step.go, database/step_test.go
Sets the default value of the following metrics to 0:
```
vela_totals{field="status",resource="services",value="failure"} 0
vela_totals{field="status",resource="services",value="killed"} 0
vela_totals{field="status",resource="services",value="pending"} 0
vela_totals{field="status",resource="services",value="running"} 0
vela_totals{field="status",resource="services",value="success"} 0
vela_totals{field="status",resource="steps",value="failure"} 0
vela_totals{field="status",resource="steps",value="killed"} 0
vela_totals{field="status",resource="steps",value="pending"} 0
vela_totals{field="status",resource="steps",value="running"} 0
vela_totals{field="status",resource="steps",value="success"} 0
```
This resolves the scenario where metrics are outdated/not present throughout the lifecycle of …
=> fix(metrics): set default values to 0

database/service.go, database/step.go, router/middleware/payload.go, router/middleware/worker.go, router/middleware/worker/worker.go
A continuation of https://github.com/go-vela/server/pull/270
The above change was intended to address **ALL** reported linter issues in the codebase.
At the time that change was submitted, the `golangci` report was showing no issues:
https://github.com/go-vela/server/runs/1816270741
Unsure if that old report was inaccurate or if these new linter issues were added after the fact.
At any rate, this adds a few `nolint` comments and some `.` at the end of comments to address these.
=> chore: linter fixes v2

api/service.go, api/step.go, go.mod, go.sum
Dependent on https://github.com/go-vela/types/pull/151
This will update the server to apply pipeline resource environment variables after they are created in the database.
Currently, in a typical webhook workflow, the server is responsible for:
* processing the webhook
* compiling the pipeline
* creating all pipeline resources (`services` and `steps`) in the database
* publishing the build to the queue
However, after the resources are created in the database, we don't update the environment variables for that resource.
This leads to the containers for those resources having incomplete data i.e.
```
VELA_STEP_NAME=
VELA_STEP_IMAGE=
VELA_SERVICE_NAME=
VELA_SERVICE_IMAGE=
```
This will call the intended `Environment()` function for the resource and inject into the environment after they are …
=> feat: set service/step environment after database creation

database/log.go, database/log_test.go, go.mod, go.sum
Dependent on https://github.com/go-vela/types/pull/154
Before this change, we ran some builds locally and checked the size of the `logs` table in the database:
```
vela=# SELECT pg_size_pretty (pg_relation_size('logs'));
pg_size_pretty
----------------
24 kB
(1 row)
```
After this change, when we run those same builds and check the size of the `logs` table in the database:
```
vela=# SELECT pg_size_pretty (pg_relation_size('logs'));
pg_size_pretty
----------------
8192 bytes
(1 row)
```
Doing a rough calculation from the above data, we were able to shrink the size of the `logs` table to `1/3` it's original size.
i.e. `8` kB  /  `24` kB = `1/3`
> NOTE: This change **is backward compatible**. If you try fetching an uncompressed log, everything will work as expected.
>
> We'll plan to offer …
=> feat(database): compress logs to reduce storage

database/log.go
Carry over from https://github.com/go-vela/server/pull/291
After submitting the above PR, we noticed we're unable to capture logs for the entire build via API or CLI.
This change fixes that by properly handling the errors returned throughout the function.
=> fix(database): capturing list of logs for a build

cmd/vela-server/main.go, cmd/vela-server/validate.go, database/client.go, database/log.go, go.mod, go.sum
Dependent on https://github.com/go-vela/types/pull/156
This enables us to set the compression level for the `go-vela/types/database.Log.Compress()` function.
This can be set via the flag `database.compression.level` or environment variables:
* `VELA_DATABASE_COMPRESSION_LEVEL`
* `DATABASE_COMPRESSION_LEVEL`
The default compression level is set to `3` which is faster than some levels but has a cost of larger data in the database.
This also has an added benefit of being able to "turn off" log compression by passing a compression level of `0`.
Also added validation logic to ensure the compression level set is between the supported range of `-1` - `9`
=> enhance(database): support setting different compression level

cmd/vela-server/main.go, cmd/vela-server/validate.go, database/client.go, database/secret.go, docker-compose.yml, go.mod, go.sum
Dependent on https://github.com/go-vela/types/pull/160
Related to:
* https://github.com/go-vela/server/pull/212
* https://github.com/go-vela/server/pull/216
* https://github.com/go-vela/server/pull/274
This change will re-introduce encryption for secret values that are stored in the Vela database.
We've decided to use the Advanced Encryption Standard (`AES`) with a `256` bit key (a.k.a. `AES-256`):
https://en.wikipedia.org/wiki/Advanced_Encryption_Standard
> NOTE: This change is backward compatible. If you try fetching an unencrypted secret, everything will work as expected.
>
> We'll plan to offer some sort of utility that will assist in encrypting all existing secrets in the database.
=> feat(database): encrypt secret values for enhanced security

api/repo.go
between disabling and re-enabling a repo, the default branch might be changed at the source provider. currently this does not get updated if that's the case. this change will account for that.
=> fix: update branch on re-enable

source/github/driver.go, source/github/driver_test.go, source/service.go
This adds a `Driver()` function to the `go-vela/server/source.Service` interface:
https://github.com/go-vela/server/blob/f6d8431ff556e2f694f6bc96eabb15e74622bfea/source/service.go#L19-L21
And then we implement this function for each supported `source` service:
https://github.com/go-vela/server/blob/f6d8431ff556e2f694f6bc96eabb15e74622bfea/source/github/driver.go#L9-L12
=> feat: add source.Driver() function

secret/native/driver.go, secret/native/driver_test.go, secret/service.go, secret/vault/driver.go, secret/vault/driver_test.go
This adds a `Driver()` function to the `go-vela/server/secret.Service` interface:
https://github.com/go-vela/server/blob/bae5e65e66561cf972bdde0aab515ad7f6fd520b/secret/service.go#L14-L16
And then we implement this function for each supported `secret` service:
https://github.com/go-vela/server/blob/bae5e65e66561cf972bdde0aab515ad7f6fd520b/secret/native/driver.go#L9-L12
https://github.com/go-vela/server/blob/bae5e65e66561cf972bdde0aab515ad7f6fd520b/secret/vault/driver.go#L9-L12
=> feat: add secret.Driver() function

go.mod, go.sum, source/github/authentication.go, source/github/authentication_test.go
backport for https://github.com/go-vela/server/commit/311ec51868384f780acb5888b9b081ff0b8cbbaf
=> fix: add check for token

cmd/vela-server/main.go, cmd/vela-server/secret.go, docker-compose.yml, secret/flags.go, secret/secret_test.go, secret/setup.go, secret/setup_test.go
Related to https://github.com/go-vela/server/pull/316, https://github.com/go-vela/server/pull/317 and https://github.com/go-vela/server/pull/318
This updates the codebase to now utilize the `secret.New()` function call and `secret.Setup{}` type:
https://github.com/go-vela/server/blob/52e69904bb77f3258f550528b2568cf14dc74cf7/cmd/vela-server/secret.go#L17-L65
Along with this change, moved the flags for the `secret` package into the `secret.Flags{}` type:
https://github.com/go-vela/server/blob/52e69904bb77f3258f550528b2568cf14dc74cf7/secret/flags.go#L13-L78
> NOTE: The following flags are modified with this change:
> 
> * `vault-driver` -> `secret.vault.driver`
> * `vault-addr` -> `secret.vault.addr`
> * `vault-auth-method` -> `secret.vault.auth-method`
> * `vault-aws-role` -> …
=> refactor: switch to using secret.New()

cmd/vela-server/metadata.go
Leftover work from https://github.com/go-vela/server/pull/331 and https://github.com/go-vela/server/pull/333
This updates the flag names used to create the `github.com/go-vela/types.Metadata{}` struct.
This should have been included in the above PRs but was missed.
=> fix: creating server metadata from flags

database/build.go, database/database.go, go.mod, go.sum
Based off of https://github.com/go-vela/sdk-go/pull/97#pullrequestreview-625404169
Related to https://github.com/go-vela/mock/pull/111 and https://github.com/go-vela/types/pull/167
This updates the `github.com/go-vela/server/database` package to use the `BuildQueue{}` type from `github.com/go-vela/types`
=> feat: use BuildQueue{} from go-vela/types

go.mod, go.sum
This updates the `github.com/go-vela/types` dependency to the latest version available.
This pulls in the most recent changes introduced from https://github.com/go-vela/types/pull/166
=> chore: update go-vela/types to latest

api/build.go
Part of the effort for https://github.com/go-vela/community/issues/144
This enables updating the `Enqueued` field for the `build` resource in Vela.
This should resolve part of the linked issue above where the `VELA_BUILD_ENQUEUED` environment variable is empty.
=> fix(api): enable updating build enqueued field

database/postgres/ddl/build.go, database/postgres/ddl/hook.go, database/postgres/ddl/log.go, database/postgres/ddl/repo.go, database/postgres/ddl/secret.go, database/postgres/ddl/service.go, database/postgres/ddl/step.go, database/postgres/ddl/user.go, database/postgres/ddl/worker.go
This adds the Postgres [data definition language (DDL)](https://en.wikipedia.org/wiki/Data_definition_language) for Vela.
All of the DDL is contained in the `github.com/go-vela/server/database/postgres/ddl` package.
The DDL was copied from [the existing `../../server/database/ddl/postgres`](https://github.com/go-vela/server/tree/master/database/ddl/postgres) old package structure.
This is an ongoing effort to make the `../../server/database` package conform to standards set in other packages.
=> feat(postgres): add vela resource ddl

database/sqlite/ddl/build.go, database/sqlite/ddl/hook.go, database/sqlite/ddl/log.go, database/sqlite/ddl/repo.go, database/sqlite/ddl/secret.go, database/sqlite/ddl/service.go, database/sqlite/ddl/step.go, database/sqlite/ddl/user.go, database/sqlite/ddl/worker.go
This adds the Sqlite [data definition language (DDL)](https://en.wikipedia.org/wiki/Data_definition_language) for Vela.
All of the DDL is contained in the `github.com/go-vela/server/database/sqlite/ddl` package.
The DDL was copied from [the existing `../../server/database/ddl/sqlite`](https://github.com/go-vela/server/tree/master/database/ddl/sqlite) old package structure.
This is an ongoing effort to make the `../../server/database` package conform to standards set in other packages.
=> feat(sqlite): add vela resource ddl

database/postgres/ping.go, database/postgres/ping_test.go
This adds a `Ping()` function to the `github.com/go-vela/server/database/postgres` client:
https://github.com/go-vela/server/blob/6a3ce24c9d0dbf9dda7e60c4301c20531275a781/database/postgres/ping.go#L14-L47
This function will be used to verify the ability to connect to the configured Postgres database.
This previously was a private, helper function in the old database client:
https://github.com/go-vela/server/blob/d484bc571d698e7f6b142f2023d3533d1687e699/database/client.go#L167-L189
=> feat(postgres): add Ping() to verify database connection

database/sqlite/ping.go, database/sqlite/ping_test.go
This adds a `Ping()` function to the `github.com/go-vela/server/database/sqlite` client:
https://github.com/go-vela/server/blob/08dc99dac013e512ab1b35f34bdf852febe29e9b/database/sqlite/ping.go#L14-L47
This function will be used to verify the ability to connect to the configured Sqlite database.
This previously was a private, helper function in the old database client:
https://github.com/go-vela/server/blob/d484bc571d698e7f6b142f2023d3533d1687e699/database/client.go#L167-L189
=> feat(sqlite): add Ping() to verify database connection

database/postgres/user.go, database/postgres/user_count.go, database/postgres/user_count_test.go, database/postgres/user_list.go, database/postgres/user_list_test.go, database/postgres/user_test.go
This adds a series of `user` functions to the `github.com/go-vela/server/database/postgres` client:
https://github.com/go-vela/server/blob/337b641b59daaa4cb2ae364591fcc327461277e0/database/database.go#L237-L262
https://github.com/go-vela/server/blob/master/database/user.go
> NOTE:
>
=> feat(postgres): add user database functions

database/postgres/worker.go, database/postgres/worker_count.go, database/postgres/worker_count_test.go, database/postgres/worker_list.go, database/postgres/worker_list_test.go, database/postgres/worker_test.go
This adds a series of `worker` functions to the `github.com/go-vela/server/database/postgres` client:
https://github.com/go-vela/server/blob/337b641b59daaa4cb2ae364591fcc327461277e0/database/database.go#L264-L286
https://github.com/go-vela/server/blob/master/database/worker.go
> NOTE:
>
=> feat(postgres): add worker database functions

database/postgres/hook.go, database/postgres/hook_count.go, database/postgres/hook_count_test.go, database/postgres/hook_list.go, database/postgres/hook_list_test.go, database/postgres/hook_test.go
This adds a series of `hook` functions to the `github.com/go-vela/server/database/postgres` client:
https://github.com/go-vela/server/blob/b904e4cab231ca0b54ec7ba862edb4820e5a04dc/database/database.go#L71-L96
https://github.com/go-vela/server/blob/master/database/hook.go
> NOTE:
>
=> feat(postgres): add hook database functions

database/postgres/build.go, database/postgres/build_count.go, database/postgres/build_count_test.go, database/postgres/build_list.go, database/postgres/build_list_test.go, database/postgres/build_test.go
This adds a series of `build` functions to the `github.com/go-vela/server/database/postgres` client:
https://github.com/go-vela/server/blob/b904e4cab231ca0b54ec7ba862edb4820e5a04dc/database/database.go#L14-L69
https://github.com/go-vela/server/blob/master/database/build.go
> NOTE:
>
> Almost `3/4` of the LOC found in this change are related to the unit tests written for the various functions.
=> feat(postgres): add build database functions

database/postgres/secret.go, database/postgres/secret_count.go, database/postgres/secret_count_test.go, database/postgres/secret_list.go, database/postgres/secret_list_test.go, database/postgres/secret_test.go
This adds a series of `secret` functions to the `github.com/go-vela/server/database/postgres` client:
https://github.com/go-vela/server/blob/b904e4cab231ca0b54ec7ba862edb4820e5a04dc/database/database.go#L149-L171
https://github.com/go-vela/server/blob/master/database/secret.go
> NOTE:
>
> Almost `3/4` of the LOC found in this change are related to the unit tests written for the various functions.
=> feat(postgres): add secret database functions

database/postgres/log.go, database/postgres/log_test.go
This adds a series of `log` functions to the `github.com/go-vela/server/database/postgres` client:
https://github.com/go-vela/server/blob/15ee929684fba1a4fbd5c21e45d7cfe55adfc8b7/database/database.go#L98-L117
https://github.com/go-vela/server/blob/master/database/log.go
> NOTE:
>
=> feat(postgres): add log database functions

database/postgres/step.go, database/postgres/step_count.go, database/postgres/step_count_test.go, database/postgres/step_list.go, database/postgres/step_list_test.go, database/postgres/step_test.go
Dependent on https://github.com/go-vela/server/pull/373
This adds a series of `step` functions to the `github.com/go-vela/server/database/postgres` client:
https://github.com/go-vela/server/blob/15ee929684fba1a4fbd5c21e45d7cfe55adfc8b7/database/database.go#L173-L203
https://github.com/go-vela/server/blob/master/database/step.go
> NOTE:
>
=> feat(postgres): add step database functions

database/postgres/service.go, database/postgres/service_count.go, database/postgres/service_count_test.go, database/postgres/service_list.go, database/postgres/service_list_test.go, database/postgres/service_test.go
Dependent on https://github.com/go-vela/server/pull/373
This adds a series of `service` functions to the `github.com/go-vela/server/database/postgres` client:
https://github.com/go-vela/server/blob/15ee929684fba1a4fbd5c21e45d7cfe55adfc8b7/database/database.go#L205-L235
https://github.com/go-vela/server/blob/master/database/service.go
> NOTE:
>
=> feat(postgres): add service database functions

api/build.go, cmd/vela-server/database.go, database/build.go, database/build_test.go, database/database.go
This updates the codebase to now utilize the `github.com/go-vela/server/database/postgres.New()` function:
https://github.com/go-vela/server/blob/82a4db624dd03940accdfd6d795be036271ca90e/cmd/vela-server/database.go#L33-L48
Along with this change, comes a small update to the order of values provided for two existing database functions:
https://github.com/go-vela/server/blob/82a4db624dd03940accdfd6d795be036271ca90e/database/database.go#L40-L45
In the old database client, these previously were declared like so:
https://github.com/go-vela/server/blob/7c7205ca14d4d99d976f8d35f5f97fd0aa3d7b8b/database/database.go#L40-L45
The two `int` values provided to those functions …
=> refactor(database)!: switch to use postgres.New()

database/sqlite/sqlite.go, database/sqlite/sqlite_test.go
This adds a `setupDatabase()` helper function to the `github.com/go-vela/server/database/sqlite` client:
https://github.com/go-vela/server/blob/98dbcb5221347113ed349e4193350761ca3dddd3/database/sqlite/sqlite.go#L110-L143
This function will be used to setup the database connections with their intended settings:
* https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime
* https://golang.org/pkg/database/sql/#DB.SetMaxIdleConns
* https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns
This previously was a private, helper function in the old database client which I've slightly modified:
https://github.com/go-vela/server/blob/b7742462653923b5e1c263e8f8f6695e15c81964/databas …
=> feat(sqlite): add setupDatabase() to setup connections

database/sqlite/build_test.go, database/sqlite/hook_test.go, database/sqlite/log_test.go, database/sqlite/secret_test.go, database/sqlite/service_test.go, database/sqlite/sqlite.go, database/sqlite/sqlite_test.go, database/sqlite/step_test.go, database/sqlite/user_test.go, database/sqlite/worker_test.go
Dependent on https://github.com/go-vela/server/pull/405
This adds a `createTables()` helper function to the `github.com/go-vela/server/database/sqlite` client:
https://github.com/go-vela/server/blob/92f49dc0141a376023b0384c175539d55a8f6ba6/database/sqlite/sqlite.go#L156-L216
This function will be used to create the data tables in the database.
This previously was a private, helper function in the old database client which I've slightly modified:
https://github.com/go-vela/server/blob/b7742462653923b5e1c263e8f8f6695e15c81964/database/client.go#L191-L249
This change also allows us to remove the `init()` functions in the test files responsible for creating Sqlite data …
=> feat(sqlite): add createTables() to create database tables

database/postgres/build.go, database/postgres/build_test.go, database/postgres/hook.go, database/postgres/hook_test.go, database/postgres/log.go, database/postgres/log_test.go, database/postgres/repo.go, database/postgres/repo_test.go, database/postgres/secret.go, database/postgres/secret_test.go, database/postgres/service.go, database/postgres/service_test.go, database/postgres/step.go, database/postgres/step_test.go, database/postgres/user.go, database/postgres/user_test.go, database/postgres/worker.go, database/postgres/worker_test.go
Related to https://github.com/go-gorm/gorm/issues/4416
**This is a workaround to a problem found in an upstream library.**
This updates the `go-vela/server/database/postgres` client to specifically check for the rows returned from queries:
https://github.com/go-vela/server/blob/95e6969b501087ab414fca37f8a60ff1faed9736/database/postgres/build.go#L35-L38
You'll note that we are explicitly checking the `RowsAffected` field is equal to `0` from the result returned by GORM.
This is required due to what initially appears to be a bug in GORM (See above [go-gorm/gorm](https://github.com/go-gorm/gorm) issue for more details).
GORM no longer returns `record not found` when a query is ran against the database and no rows are returned.
=> fix(postgres): add workaround for gorm record not found

database/sqlite/build.go, database/sqlite/build_test.go, database/sqlite/hook.go, database/sqlite/hook_test.go, database/sqlite/log.go, database/sqlite/log_test.go, database/sqlite/repo.go, database/sqlite/repo_test.go, database/sqlite/secret.go, database/sqlite/secret_test.go, database/sqlite/service.go, database/sqlite/service_test.go, database/sqlite/step.go, database/sqlite/step_test.go, database/sqlite/user.go, database/sqlite/user_test.go, database/sqlite/worker.go, database/sqlite/worker_test.go
Related to https://github.com/go-gorm/gorm/issues/4416
**This is a workaround to a problem found in an upstream library.**
This updates the `go-vela/server/database/sqlite` client to specifically check for the rows returned from queries:
https://github.com/go-vela/server/blob/c7e995a6546ba08f2c977428cd79a8a3ed726a32/database/sqlite/build.go#L35-L38
You'll note that we are explicitly checking the `RowsAffected` field is equal to `0` from the result returned by GORM.
This is required due to what initially appears to be a bug in GORM (See above [go-gorm/gorm](https://github.com/go-gorm/gorm) issue for more details).
GORM no longer returns `record not found` when a query is ran against the database and no rows are returned.
=> fix(sqlite): add workaround for gorm record not found

cmd/vela-server/database.go
This updates the codebase to now utilize the `github.com/go-vela/server/database/sqlite.New()` function:
https://github.com/go-vela/server/blob/157109c980447bbca2b5f13cdeb8786bfa363849/cmd/vela-server/database.go#L51-L66
=> refactor(database)!: switch to use sqlite.New()

database/setup.go, database/setup_test.go
This ensures we validate the compression level field for logs stored in the database.
This is carried over from the previously used validation logic for database configuration:
https://github.com/go-vela/server/blob/64ac1023e85df61fe83d52d1eeda103869c21634/cmd/vela-server/validate.go#L116-L165
=> enhance(database): validate compression level in setup

cmd/vela-server/database.go, cmd/vela-server/main.go, cmd/vela-server/metadata.go, cmd/vela-server/validate.go, database/flags.go, docker-compose.yml
Leftover work from https://github.com/go-vela/community/issues/248
Related to https://github.com/go-vela/server/pull/398, https://github.com/go-vela/server/pull/411 and https://github.com/go-vela/server/pull/416.
This updates the codebase to now utilize the `database.New()` function call and `database.Setup{}` type:
https://github.com/go-vela/server/blob/01a3e68116b41e9f3268cda868b37ebefd9d3bb4/cmd/vela-server/database.go#L15-L34
Along with this change, moved the flags for the `database` package into the `database.Flags{}` type:
https://github.com/go-vela/server/blob/01a3e68116b41e9f3268cda868b37ebefd9d3bb4/database/flags.go#L14-L78
> NOTE: The following flags are modified with this change:
> 
> * `database.config` -> `database.addr`
=> refactor!: switch to using database.New()

api/webhook.go
Related to https://github.com/go-vela/server/pull/393
This change will ensure that the `repo.Counter` and `build.Number` fields are set properly.
This is required because Vela attempts to utilize a "retry" logic when processing webhooks.
In order to ensure we set the proper `repo.Counter` and `build.Number` fields, we need to move the logic responsible for incrementing these values inside the retry logic.
=> fix(api): setting repo counter and build numbers

database/postgres/secret.go, database/postgres/secret_test.go, database/sqlite/secret.go
Related to https://github.com/go-vela/types/pull/166
Currently, there is a bug when attempting to create `secrets` in Vela.
If you attempt to create a `repo` or `shared` secret, you may experience errors from the database like:
```
Status 500 (unable to create secret <secret> for native service: ERROR: duplicate key value violates unique constraint "secrets_type_org_team_name_key" (SQLSTATE 23505))
```
OR
```
Status 500 (unable to create secret <secret> for native service: ERROR: duplicate key value violates unique constraint "secrets_type_org_repo_name_key" (SQLSTATE 23505))
```
This only happens when you attempt to create a secret that has the same `name` and is in the same `org`.
An example to replicate the behavior for `repo` secrets:
```
$ vela add secret --secret.engine native …
```
=> fix(database): creating secrets with empty fields

api/build.go, source/github/repo.go
This updates the `PUT /api/v1/repos/:org/:repo/builds/:build` endpoint in Vela.
Currently, if a build is `canceled`, we don't actually update the commit `status` in the source system like other statuses.
This is controlled through the `github.com/go-vela/api/UpdateBuild()` function:
https://github.com/go-vela/server/blob/35c522e3d72e7781abde74056303eb09a63beb86/api/build.go#L896-L913
And the `github.com/go-vela/server/source.Status()` function doesn't account for the `canceled` status either:
https://github.com/go-vela/server/blob/35c522e3d72e7781abde74056303eb09a63beb86/source/github/repo.go#L203-L221
This augments these functions for the API endpoint to account for the `canceled` status when setting it for the commit.
=> enhance(build): set canceled commit status in source system

cmd/vela-server/main.go
This updates the `github.com/go-vela/server` app to output the version information to stdout on startup:
```sh
$ docker logs server
{
"canonical": "v0.8.2",
"major": 0,
"minor": 8,
"patch": 2,
"metadata": {
"architecture": "amd64",
"build_date": "2021-06-15T08:57:00Z",
"compiler": "gc",
"git_commit": "7ed708324825cc05e596306093a2855da47330c7",
"go_version": "go1.16.5",
"operating_system": "linux"
}
}
<more logs>
```
=> feat: output version info to stdout

database/postgres/secret.go, database/postgres/secret_test.go, database/sqlite/secret.go
Related to https://github.com/go-vela/types/pull/166
Based off of https://github.com/go-vela/server/pull/428
Currently, there is a bug when attempting to update `secrets` in Vela.
If you attempt to update a `repo` or `shared` secret, you may experience errors from the database like:
```
Status 500 (unable to update secret <secret> for native service: ERROR: duplicate key value violates unique constraint "secrets_type_org_team_name_key" (SQLSTATE 23505))
```
OR
```
Status 500 (unable to update secret <secret> for native service: ERROR: duplicate key value violates unique constraint "secrets_type_org_repo_name_key" (SQLSTATE 23505))
```
This only happens when you attempt to update a secret that has the same `name` and is in the same `org`.
An example to replicate the behavior for `repo` …
=> fix(database): updating secrets with empty fields

cmd/vela-server/source.go, source/flags.go, source/github/github.go, source/github/github_test.go, source/github/opts.go, source/github/opts_test.go, source/setup.go, source/setup_test.go, source/source_test.go
This change allows the Vela administrator to override the list of [OAuth scopes](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) by setting the `VELA_SOURCE_SCOPES` variable.
closes https://github.com/go-vela/community/issues/274
=> enhance(source): allow admin to customize oauth scopes

database/postgres/driver.go, database/postgres/driver_test.go, database/service.go, database/sqlite/driver.go, database/sqlite/driver_test.go
This adds a `Driver()` function to the `go-vela/server/database.Service` interface:
https://github.com/go-vela/server/blob/9de2c808716b56d21b8c27fdb0877a1e09523bb6/database/service.go#L16-L18
And then we implement this function for each supported `database` service:
https://github.com/go-vela/server/blob/9de2c808716b56d21b8c27fdb0877a1e09523bb6/database/postgres/driver.go#L9-L12
https://github.com/go-vela/server/blob/9de2c808716b56d21b8c27fdb0877a1e09523bb6/database/sqlite/driver.go#L9-L12
=> feat: add database.Driver() function

api/user.go
This resolves the issue where the `/api/v1/user/source/repos` endpoint was incorrectly returning `active: false` for some repositories when the given user had >= 100 repos returned by the aforementioned endpoint.
=> fix(api): assume more results exist if list not empty

cmd/vela-server/database.go, database/database_test.go, database/flags.go, database/postgres/opts.go, database/postgres/opts_test.go, database/postgres/postgres.go, database/postgres/postgres_test.go, database/setup.go, database/setup_test.go, database/sqlite/opts.go, database/sqlite/opts_test.go, database/sqlite/sqlite.go, database/sqlite/sqlite_test.go
This adds a new `database.skip_creation` boolean flag to the `github.com/go-vela/server/database` package.
The intention of this flag is to enable skipping the creation of DDL objects (tables and indexes) in the database.
This flag can also be set via environment variables with:
* `VELA_DATABASE_SKIP_CREATION`
* `DATABASE_SKIP_CREATION`
This flag can also be set via a value in a file with the path `/vela/database/skip_creation`.
The use-case for this functionality is to enable Vela to support databases without admin access to that database.
This setup can happen when running Vela with a database that has extra security controls preventing DDL changes.
> NOTE: Most of the LOC found in this change are related to the tests added for this new flag.
=> feat(database): support skipping creation of tables and indexes

go.mod, go.sum, router/middleware/token/token.go, router/middleware/token/token_test.go
Closes https://github.com/go-vela/community/issues/352
This updates the library the server uses to handle [JWT](https://jwt.io/) token processing.
Currently, we're using `github.com/dgrijalva/jwt-go`.
After this change, we'll be using `github.com/golang-jwt/jwt`.
This resolves the known vulnerability in the old JWT library reported by Dependabot:
https://github.com/go-vela/server/security/dependabot/go.mod/github.com%2Fdgrijalva%2Fjwt-go/open
> **CVE-2020-26160** - `high severity`
>
> **Vulnerable versions**: `<= 3.2.0`
>
> **Patched version**: `No fix`
>
> [jwt-go](https://github.com/dgrijalva/jwt-go) allows attackers to bypass intended access restrictions in situations with []string{} for m["aud"] (which is allowed by the specification). Because the type assertion fails, "" is the value …
=> fix(deps): address vulnerable jwt-go library

api/build.go
on restart we incremented the build counter ***after*** setting the link property which is utilized in the UI, resulting in the link pointing to the previous build.
this PR moves the build increment logic up to be called before we set the link for the build within the handler for the restart endpoint.
in my testing, this solved the issue for the below:
fixes: https://github.com/go-vela/community/issues/353
fixes: https://github.com/go-vela/community/issues/322
=> fix: correct build number on restart

database/postgres/build_list.go, database/postgres/build_list_test.go, database/sqlite/build_list.go, database/sqlite/build_list_test.go
Fixes https://github.com/go-vela/community/issues/354
This will sort the list of `builds` returned for a specific `org` by the `build.started` timestamp.
Currently, we're sorting the list of `builds` for a specific `org` by `build.number`.
The problem this causes is the `builds` for some `repos` may not appear because they have a smaller `build.number`.
Let's say we have two `repos` in an `org` named `test`:
* `test/foo`
* `test/bar`
And let's say `test/foo` has ran 200 `builds` while `test/bar` has only ran 100 `builds`.
If you attempt to capture a list of builds for `test`, you'll only see the builds for `test/foo`.
This happens because the `builds` for `test/foo` all have a higher `build.number` field than the `builds` for `test/bar`.
=> fix(database): sort org build list by started timestamp

database/postgres/build_list.go, database/postgres/build_list_test.go, database/sqlite/build_list.go
modification of https://github.com/go-vela/server/pull/464 that utilizes `created` instead of `started` for the sorting.
intent is to prevent items jumping in the list since it's more likely for `started` to be `0` (top of the list) and then updated, whereas `created` is typically set when added to the db.
=> fix(database): sort by created instead of started

database/postgres/build_list.go, database/postgres/build_list_test.go, database/sqlite/build_list.go
While https://github.com/go-vela/server/pull/469 helped, it's possible for the DB to return data in an inconsistent order when the `created` value is the same for two different builds. This PR adds a second order using the primary key (`id`) to help deliver a consistent order.
=> fix: add second order to ensure order consistency

api/build.go, api/pipeline.go, api/webhook.go, cmd/vela-server/compiler.go, go.mod, go.sum, queue/redis/redis_test.go, router/middleware/compiler.go, router/middleware/compiler_test.go
a few tweaks had to be made to imports to eliminate legacy dependencies and circular dependecies. additionally, one test required functions from the sdk-go project. we've inlined them for now but could see them be part of go-vela/types potentially.
=> chore: release v0.11.0-rc1

database/postgres/build.go, database/sqlite/build.go, database/sqlite/build_test.go
This resolves an issue with the `/api/v1/admin/builds/queue` endpoint.
Currently, a problem exists with the above endpoint if no `pending` or `running` builds exist in the database.
if you send a `GET` request to the above URL in that scenario, you'll receive a `500 Internal Server Error` code.
Along with this HTTP status code, you'll receive the following error message:
```
{"error": "unable to capture all running and pending builds: record not found"}
```
The reason for this behavior is due to how the [GetPendingAndRunningBuilds()](https://github.com/go-vela/server/blob/13dcae99a55ff874c06fb7d97c9bdabe604dc288/api/admin/build.go#L98-L106) behaves in the `database` package.
When the function is called, we execute a query and perform a check to see if any results are returned: …
=> fix: capturing empty build queue

.github/workflows/validate.yml, Makefile, api/authenticate.go, api/badge.go, api/build.go, api/deployment.go, api/login.go, api/logout.go, api/metrics.go, api/secret.go, api/service.go, api/stream.go, api/token.go, api/version.go, api/webhook.go, api/worker.go, go.mod, go.sum, router/router.go
closes https://github.com/go-vela/community/issues/432
depends on https://github.com/go-vela/types/pull/208 (`/version` endpoint returns a Version object)
contains:
* various fixes to spec annotations (spelling, correctness, missing info, etc)
* adds spec validation to `validate` workflow in GitHub Actions
* consistent import sort in `/api` package
no code was changed, but theses edits should result in the automation producing a valid and more accurate API spec.
_note: `validate` workflow will fail due to new spec validation until the dependent PR is merged and `/types` import is updated_
=> fix(api-spec): ensure api spec validates

Makefile, version/version.go
This change slightly modifies two pieces from the version output.
This first part is updating the version output to use a fallback value for the semantic tag of `v0.0.0`.
This should prevent the possibility of a panic happening if the tag info isn't captured properly:
https://github.com/go-vela/server/blob/aff96b30eefd6d9425758088f97e42be1fd80243/Makefile#L17-L21
The second part is using Go's `runtime.Version()` function to capture the version of `go` the app is built with:
https://pkg.go.dev/runtime#Version
Since we're relying on that function from the `runtime` library, we no longer need to capture that info in the `Makefile`.
Previously, we used to run the `go version` command and parse the value from the output:
https://github.com/go-vela/server/blob/aff96b30eefd6d9425758088f97e42be1fd …
=> enhance: setting version information

database/postgres/ddl/build.go, database/postgres/postgres.go, database/postgres/postgres_test.go, database/sqlite/ddl/build.go, database/sqlite/sqlite.go
Used for reporting - e.g. `where created > $some_epoch` to quickly and cheaply limit querying recent build metrics.
=> feat: add index on builds.created

.github/workflows/build.yml, .github/workflows/prerelease.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/reviewdog.yml, .github/workflows/spec.yml, .github/workflows/test.yml, .github/workflows/validate.yml, go.mod
Updates Go to 1.17, GitHub Actions pipelines included.
xref: https://github.com/go-vela/types/pull/221
=> chore(deps): update go to 1.17

compiler/registry/github/github.go, compiler/registry/github/github_test.go, compiler/registry/github/template.go, go.mod, go.sum, scm/github/access.go, scm/github/authentication.go, scm/github/changeset.go, scm/github/deployment.go, scm/github/github.go, scm/github/github_test.go, scm/github/repo.go, scm/github/webhook.go
[Released 1/12/2022](https://github.com/google/go-github/releases/tag/v42.0.0), this newest version has a specific functionality that was added to help with [this PR](https://github.com/go-vela/server/pull/556) (See: Add Changes field to Repository Event).
=> chore(github): update go-github to latest version (v42)

secret/vault/refresh.go
Related to https://github.com/go-vela/community/issues/473
This is a backport of https://github.com/go-vela/server/pull/570 into the `v0.11.x` codebase.
To create the backport, a new `v0.11.1` branch was created from the `v0.11.0` release for Vela.
Then, I created a new `backport/fix/secret/vault` branch based off the `v0.11.1` branch to add the functionality needed.
Once the functionality is accepted and merged, a new `v0.11.1` release will be cut from the `v0.11.1` branch.
=> backport(secret/vault): update strategy to refresh token

secret/native/update.go, secret/native/update_test.go
Actually setting the metadata fields when a secret is updated. I also made the existing test actually test for an update so this hopefully won't happen in the future.
=> fix(secrets): actually set updated_at and updated_by fields

database/postgres/ddl/build.go
Related to [this change](https://github.com/go-vela/types/pull/231).
=> fix(build)!: increase error limit to 1000

api/secret.go
Backport for patch release `v0.12.1`. Somewhat related to https://github.com/go-vela/worker/pull/274. 
Already merged PR for this change: https://github.com/go-vela/server/pull/588
=> fix(api/secrets): reject secrets with only whitespace characters

api/repo.go
Adding `repos` to path for the swagger spec
=> fix(api/repo): fix path for GetOrgRepos in swagger spec

api/build.go, api/webhook.go
closes https://github.com/go-vela/community/issues/643
most details on this can be found in the issue above. i commented some of the changes. 
we also added some TODOs for things to look at in lieu of creating new issues to start some conversation and not lose track of it.
we are adding to top of HEAD since there were only two minor merges that only impact tests.
=> fix(webhook): avoid panics

router/pipeline.go
Since expand pipeline aggregates information that is already available for those with read permissions, it makes sense to have the expand endpoint match that level of accessibility.
=> enhance(router/pipeline): change expand, validate, and compile to MustRead

scm/github/webhook.go
Until we give users the ability to opt-in for the `edited` action for PR events, the added webhook noise is resulting in unexpected behavior. 
For example, if a user has a step:
```yaml
- name: example
image: alpine
ruleset:
event: pull_request
```
That step is ignored due to the fact that `pull_request` == `pull_request:opened, pull_request:synchronize`. Another way to say this: we accommodated legacy pull request ruleset on the yaml side but not the webhook side. 
As a band-aid, we can turn off the firehose for edited actions until we have a more robust way of handling it.
=> fix(scm/webhook): turn off pr:edited events

api/build.go, router/pipeline.go
Any pull request build ran before 0.14 will not have the action field populated, thus upon restarting, it will not run properly against steps with a `event: pull_request` ruleset.
=> fix(build/ruleset): handle legacy PR ruleset for restarted build

scm/github/webhook.go
Sometimes the webhook delivery will no longer be available due to how old it is, not whether it is in the 100 most recent. Upon failure, it's a better idea to give a general error to avoid confusing the user.
=> fix(webhook): more general error message for redelivery failure

api/admin/build.go, api/admin/deployment.go, api/admin/hook.go, api/admin/repo.go, api/admin/secret.go, api/admin/service.go, api/admin/step.go, api/admin/user.go, router/admin.go
Closes https://github.com/go-vela/community/issues/713
Platform admins will no longer be able to pull all sensitive resources (such as secrets, repos, and users) as well as resources which have typically very large tables in the DB (builds, steps, services).
=> enhance(admin/api): remove collect all endpoints for DB resources

go.mod, go.sum, queue/redis/pop.go, queue/redis/pop_test.go, queue/redis/push.go, queue/redis/push_test.go, queue/redis/redis.go
**NOTE** this PR updates redis to v9 which requires the following changes: 
- `MaxConnAge` changed to `ConnMaxLifetime`
- `IdleTimeout` changed to `ConnMaxIdleTime ` 
- `IdleCheckFrequency` was replaced in favor of `MaxIdleConns`
- `RPush` no longer supports adding `nil` items, so a check has been added to the `Push` wrapper. tests have been updated to reflect the change. see: https://github.com/redis/go-redis/pull/1960 and https://github.com/redis/go-redis/releases/tag/v9.0.2
see the [CHANGELOG](https://github.com/redis/go-redis/blob/master/CHANGELOG.md) for more information
=> chore(queue): update go-redis to v9

router/middleware/perm/perm.go, router/middleware/perm/perm_test.go
Initial [build token implementation](https://github.com/go-vela/server/pull/765) failed to address repos with a private visibility status. Since the worker is not treated as a platform admin, it will fail the SCM check to verify read permissions. 
This fix adds logic to allow workers to access `MustRead` endpoints from private repos so long as the build token is still accurate.  I also added a related test.
I double checked the worker's flow and determined that it does not call endpoints behind `MustWrite` or `MustAdmin`, so I've decided to leave the build token logic out of those functions.
=> fix(perm): allow workers with build tokens to access MustRead() for private visibility repos

database/user/table.go
It was determined that the bump in column size for the `token` value was not actually necessary. Better to be space-conscious with table sizes.
=> fix(database): revert column size bump to users token values

api/pipeline/template.go
The feature that allowed for same-repo, same-commit templates was not accounted for in this section of the API. Adding a fix so users can view / expand their pipelines in the UI.
Closes https://github.com/go-vela/community/issues/769
=> fix(pipelines): support for file template type when gathering templates

api/build.go, api/webhook.go, queue/redis/route.go, queue/redis/route_test.go
This change will verify that the user provided queue route matches the configured routes. This prevents poorly routed builds from sitting on the queue forever.
I also added error wrapping to `cleanBuild` because "unable to publish to queue" was too generic and only makes support for the product more challenging for platform admins.
Before: 
After:
=> enhance(queue): validate queue route and add error wrapping to clean build

api/metrics.go, queue/redis/length.go, queue/redis/length_test.go, queue/service.go
There have been several cases where a build has found itself in a `pending` state due to some error in the webhook flow (typically around `publishToQueue`). These builds never make it to the queue and are still left as `pending`. This additional query to the metrics endpoint gives a much more accurate representation of queue size.
=> enhance(metrics): gather queued builds

api/worker.go
If using the registration auth flow, this extra validation check will ensure that the host name configured in the token claims matches the host name of the worker that is being updated / created.
=> enhance(api/worker): validate host name in claims against input

internal/token/parse.go, internal/token/parse_test.go, router/middleware/claims/claims_test.go
Due to some clock skew, we began seeing `token used before issued` errors. We noticed [this issue](https://github.com/golang-jwt/jwt/issues/98) in the JWT library, which appears to be resolved in their upcoming `v5` release. In that release, they will be making `issued_at` unchecked by default, due to its optional nature. I elaborated on this in the code comments as well.
=> fix(jwt): set issued_at to nil prior to validating claims

api/metrics.go
Just noticed I left this out from https://github.com/go-vela/server/pull/802
=> fix(metrics/spec): add queued_build_count to spec

api/repo/create.go, api/repo/repair.go, scm/github/repo.go, scm/github/repo_test.go, scm/github/webhook.go, scm/service.go
With the release of [go-github/v51](https://github.com/google/go-github/releases/tag/v51.0.0), the `ValidatePayload` method now _requires_ secret validation in order to capture a payload ([ref](https://github.com/google/go-github/commit/b1c53f808b2218b2572fa7f8a8b4b4401a02ca96)). 
Since our webhook validation occurs [later](https://github.com/go-vela/server/blob/3fec46cbef8ae8224d7cad31680e96e4b5513498/api/webhook.go#L250), when we actually have our webhook secret, we cannot grab this payload unless we call `ValidatePayloadFromBody` with empty signature and secret values instead. 
Lastly, in [this change](https://github.com/go-vela/server/pull/679), I failed to account for situations where a repo was being re-enabled / repaired, and thus the `init` webhook would not have a number value of …
=> fix(scm): handle new go-github validation changes and ensure correct number for init hook

api/webhook.go
Calling `GetRepoForOrg` later in the webhook flow causes the topic and branch setting done earlier to be overwritten. Relocating so that they are properly updated.
=> fix(webhook): relocate topics & branch setting to avoid overwrite

api/repo/create.go, scm/github/repo.go, scm/github/repo_test.go
Noticed that `init` webhooks were set to a failed status.
Also saw that when we already have a record of a repo and are in the process of re-enabling it, we should make sure the events specified for that record match what we send the SCM, rather than the default events.
=> fix(scm): correct init hook status and send accurate events

api/webhook.go, scm/github/testdata/hooks/push.json, scm/github/testdata/hooks/push_no_sender.json, scm/github/webhook.go, scm/github/webhook_test.go
Now we can set topics from push events. Though we keep this field updated on repository events, some repos enabled prior to the v0.19 release will not benefit from that unless they manually change their topics.
=> fix(deps): update process push webhook to account for changes in v52

compiler/native/substitute.go, compiler/native/substitute_test.go, go.mod, go.sum
Reverting: https://github.com/go-vela/server/pull/793 due to reason in title.
Also including upgrade to `v0.19.2` types dependency
=> revert(envsubst): roll back envsubst library upgrade due to multiline secret errors

router/middleware/user/user.go, router/router.go
Upon logging out, server would panic due to claims not being established prior to user. This solves that.
=> fix(router): establish claims before user on logout

api/admin/clean.go, database/build/clean.go, database/build/clean_test.go, database/build/interface.go, database/service/clean.go, database/service/clean_test.go, database/service/interface.go, database/step/clean.go, database/step/clean_test.go, database/step/interface.go, mock/server/build.go, mock/server/server.go, router/admin.go
Oftentimes during upgrades, network blips, or failures in worker-server communication, builds, steps, and or services, never make it out of `pending` or `running` states. This endpoint gives platform admins the power to clean build resources that have been pending or running for longer than a specified time as well as give the builds a specified error message.
=> feat(api/admin): add endpoint to clean pending / running builds

mock/server/build.go
When trying to test a `0` for the query param, it won't add it to the url string [here](https://github.com/go-vela/sdk-go/blob/4c6fc715258ca3188897179b140672fd7bbf03a7/vela/client.go#L260-L264) where we build the query string in the SDK. This change makes sure the `500` response is actually testable.
=> fix(mock): correct query param mocks

cmd/vela-server/schedule.go
fixes a double-increment bug. scheduled builds get assigned counter+2 
if it helps, here's the webhook builds code https://github.com/go-vela/server/blob/main/api/webhook/post.go#L472-L484
=> fix(schedules): increment repo counter after read

api/log/create_service.go, api/log/create_step.go, api/log/update_service.go, api/log/update_step.go, api/service/plan.go, api/step/plan.go, database/log/count_build_test.go, database/log/count_test.go, database/log/create.go, database/log/create_test.go, database/log/delete_test.go, database/log/get_service_test.go, database/log/get_step_test.go, database/log/get_test.go, database/log/interface.go, database/log/list_build_test.go, database/log/list_test.go, database/log/update.go, database/log/update_test.go, mock/server/log.go
Sort of a revert of https://github.com/go-vela/server/pull/865 but this PR goes further and simply does not bother returning the log object on a successful `POST` or `PUT`.
I did a little bit of research on general HTTP practices, and it appears that this question of returning data on `200` and `201` codes is pretty much context-driven. Given that `CreateStepLog` + `CreateServiceLog` arguably shouldn't exist for user access and `UpdateStepLog` + `UpdateServiceLog` are locked behind worker permissions / platform admins, I think it's safe to say continuously returning the database object is not worth the overhead. 
The [only logic that utilizes this returned value](https://github.com/go-vela/worker/blob/0bac3d636f4bb0a35ea5b2b020d6d0d7db6343f0/executor/linux/step.go#L326-L331) in the entire …
=> enhance(log)!: do not return log object for POST and PUT requests

api/schedule/create.go, api/schedule/update.go, cmd/vela-server/schedule.go, database/schedule/interface.go, database/schedule/update.go, database/schedule/update_test.go, docker-compose.yml
Existing schedule:
```json
{
"id": 1,
"repo_id": 1,
"active": true,
"name": "hourly",
"entry": "0 * * * *",
"created_at": 1641314085,
"created_by": "octokitty",
"updated_at": 1641314085,
"updated_by": "octokitty",
"scheduled_at": 0
}
```
Old:
```go
s := existingSchedule
s.SetScheduledAt(now)
_ := db.UpdateSchedule(s)
s, _ := db.GetSchedule(existingSchedule)
fmt.Println(s.GetUpdatedAt())
// ... <now> ...
```
New:
```go
s := existingSchedule
s.SetScheduledAt(now)
_ := db.UpdateSchedule(s)
s, _ := db.GetSchedule(existingSchedule)
fmt.Println(s.GetUpdatedAt())
// ... 1641314085 ...
```
GORM auto updates `updated_at`. This change ensures that that field is still relevant.
RFC: separate DB function altogether, or will this boolean be fine?
=> fix(schedules): updated_at automatically updates to any change to row

docker-compose.yml
[Deprecation notice](https://hub.docker.com/_/vault)
=> fix(compose): use hashicorp/vault docker repo

api/build/list_org.go, api/build/list_repo.go
adds "schedule" as an allowed event type for endpoints that accept event filter in query:
* /api/v1/repos/{org}/builds
* /api/v1/repos/{org}/{repo}/builds
also, adds missing query param filters to docs for `/api/v1/repos/{org}/builds`.
=> fix(api): support schedule in filter

api/schedule/create.go, api/schedule/create_test.go, api/schedule/update.go, docker-compose.yml
Prior to this change, the entry `0 1,2,10,12 * * *` with a `VELA_SCHEDULE_MINIMUM_FREQUENCY` of `180m` would be considered valid if you added the schedule between the hours of 12:00 Zulu time and 1:00 Zulu time the next day.  Won't catch all cases, but I figured it would catch more than enough.
Also set `updated_by` in the update schedule endpoint.
=> fix(api/schedule): make validateEntry more strict and set updated_by using claims

database/build/build_test.go, database/build/clean_test.go, database/schedule/schedule_test.go, database/schedule/update_test.go, database/secret/secret_test.go, database/secret/update_test.go, database/service/clean_test.go, database/service/service_test.go, database/step/clean_test.go, database/step/step_test.go
This'll remove the occasional failed test due to a timestamp being off by 1
=> fix(db tests): use lenient timestamp check for time.Now query matching

api/pipeline/compile.go, api/pipeline/expand.go, api/pipeline/validate.go, compiler/engine.go, compiler/native/compile.go, compiler/native/compile_test.go, compiler/native/expand.go, compiler/native/native.go, compiler/native/native_test.go
When leveraging `vela validate pipeline --template --template-file exampleOne:one.yml,exampleTwo:two.yml` in a nested template sense (exampleTwo is called within exampleOne), the current implementation of local template retrieval can't handle that. 
By adding local templates to the engine itself, we can access the provided info at any time during compilation, allowing proper local retrieval deep within a template chain.
=> fix(compiler): convert local templates to an engine field for nested templates

api/repo/create.go, scm/github/repo.go, scm/github/repo_test.go
Corresponds with issue "when enabling a private repo in scm, set it to private in vela as well" #784: 
[https://github.com/go-vela/community/issues/784]
=> fix: getting visbility to match on vela and SCM

api/admin/service.go, api/build/cancel.go, api/build/clean.go, api/service/create.go, api/service/plan.go, api/service/update.go, database/integration_test.go, database/service/clean_test.go, database/service/count_build_test.go, database/service/count_test.go, database/service/create.go, database/service/create_test.go, database/service/delete_test.go, database/service/get_build_test.go, database/service/get_test.go, database/service/interface.go, database/service/list_build_test.go, database/service/list_image_test.go, database/service/list_status_test.go, database/service/list_test.go, database/service/update.go, database/service/update_test.go, router/middleware/service/service_test.go
Continuing effort from these: https://github.com/go-vela/server/pull/861, https://github.com/go-vela/server/pull/882, https://github.com/go-vela/server/pull/884, https://github.com/go-vela/server/pull/913, https://github.com/go-vela/server/pull/915, https://github.com/go-vela/server/pull/928
=> refactor(db): return service on created and updated

api/admin/step.go, api/build/cancel.go, api/build/clean.go, api/step/create.go, api/step/plan.go, api/step/update.go, database/integration_test.go, database/step/clean_test.go, database/step/count_build_test.go, database/step/count_test.go, database/step/create.go, database/step/create_test.go, database/step/delete_test.go, database/step/get_build_test.go, database/step/get_test.go, database/step/interface.go, database/step/list_build_test.go, database/step/list_image_test.go, database/step/list_status_test.go, database/step/list_test.go, database/step/update.go, database/step/update_test.go, router/middleware/step/step_test.go
Continuing effort from these: https://github.com/go-vela/server/pull/861, https://github.com/go-vela/server/pull/882, https://github.com/go-vela/server/pull/884, https://github.com/go-vela/server/pull/913, https://github.com/go-vela/server/pull/915, https://github.com/go-vela/server/pull/928, https://github.com/go-vela/server/pull/932
=> refactor(db): return step on created and updated

docker-compose.yml, queue/flags.go
simplifying the naming based on verbosity feedback. 
lets do this before we release it.
=> chore: simplify queue env variable names

api/webhook/post.go
currently, new builds always produce build objects that have their `parent` field referencing the previous build (-1) - the exception is the very first build for which `parent` and `number` are the same value (1).
afaik, there's no reason for this and the only time these two should diverge (at least, currently) is if a build was restarted. in that case `parent` should reference the build number that was restarted. that currently works as described.
in other words, it currently looks like every build (except the very first one) is a restart of the previous build.
this change will remove the setting of the parent field on regular builds. for restarts it will continue to work as before and set the parent appropriately.
=> fix(webhook): keep parent and build number synced

api/admin/user.go, api/auth/get_token.go, api/auth/logout.go, api/user/create.go, api/user/create_token.go, api/user/delete_token.go, api/user/update.go, api/user/update_current.go, database/integration_test.go, database/user/count_test.go, database/user/create.go, database/user/create_test.go, database/user/delete_test.go, database/user/get_name_test.go, database/user/get_test.go, database/user/interface.go, database/user/list_lite_test.go, database/user/list_test.go, database/user/update.go, database/user/update_test.go, internal/token/refresh_test.go, router/middleware/claims/claims_test.go, router/middleware/perm/perm_test.go, router/middleware/pipeline/pipeline_test.go, router/middleware/user/user_test.go
Continuing effort from these: https://github.com/go-vela/server/pull/861, https://github.com/go-vela/server/pull/882, https://github.com/go-vela/server/pull/884, https://github.com/go-vela/server/pull/913, https://github.com/go-vela/server/pull/915, https://github.com/go-vela/server/pull/928, https://github.com/go-vela/server/pull/932, https://github.com/go-vela/server/pull/933
=> refactor(db): return user on created and updated

queue/flags.go
i thought i included these variables in my last tweak PR but apparently not. i noticed while writing the docs.
=> enhance: use consistent variable aliases for queue signing keys

api/build/executable.go, api/build/publish.go, api/webhook/post.go
An attempt at clearing some things up that may be confusing for first time contributors (or 50th time contributors for that matter 😅 )
=> chore(webhook): improve on some comments during the webhook flow

api/build/restart.go
[This change](https://github.com/go-vela/server/pull/859) forgot to add the new `WithCommit` option to the restart API handler. When users would restart a build that leveraged a same-commit template, it would attempt to source the template from the default branch rather than the commit.
=> fix(restart): instantiate compiler with commit

api/webhook/post.go, database/hook/get_webhook.go, database/hook/get_webhook_test.go, database/hook/interface.go, database/integration_test.go, scm/github/webhook.go, scm/github/webhook_test.go
With newer GitHub versions allowing users to transfer _and_ rename in one fell swoop, there happened to be a bug in the payloads that are sent our way.
GitHub offered this `transfer` + `rename` option with the following events under the hood (example involves the transfer of `ExampleOrg/name` to `EastonCrupper/new-name`):
```json
{
"action": "transferred",
"changes": {
"owner": {
"from": {
"user": {
"login": "EastonCrupper",
....
}
}
}
},
"repository": {
"id": 352163,
"name": "new-name",
.......
```
followed by
```json
{
"action": "renamed",
"changes": {
"repository": {
"name": {
"from": "name"
}
}
},
"repository": {
"id": 352163,
"name": "new-name",
"full_name": "EastonCrupper/new-name",
"private": false,
"owner": {
"login": "EastonCrupper",
.......
```
The issue: **we have no way to …
=> fix(webhook): repo transfer handling with renaming - support newer GitHub versions

api/webhook/post.go, database/hook/get_webhook.go, database/hook/get_webhook_test.go, database/hook/interface.go, scm/github/webhook.go, scm/github/webhook_test.go
Preparing patch release of `v0.20.2`. Includes these changes: https://github.com/go-vela/server/pull/955
=> patch(webhook): support transfer and rename

api/repo/update.go, api/scm/sync.go, api/scm/sync_org.go, scm/github/repo.go, scm/github/repo_test.go, scm/service.go
Preparing for patch `v0.20.2`. This will include these changes: https://github.com/go-vela/server/pull/953
=> patch(sync): address sync bug with update webhook call

api/pipeline/compile.go, api/pipeline/expand.go, api/pipeline/validate.go, compiler/engine.go, compiler/native/compile.go, compiler/native/compile_test.go, compiler/native/expand.go, compiler/native/native.go, compiler/native/native_test.go, go.mod, go.sum
The [patch](https://github.com/go-vela/server/pull/917) that was included in `v0.20.1` was reverted in the publishing of `v0.20.2` due to mistakes in the patching process.
This patch reintroduces the bug fix that resulted in the `v0.20.1` patch while also including all the fixes in `v0.20.2`.
It also pulls in the matching `v0.20.3` types version for consistency in the eventual `v0.20.3` server release.
=> patch(compiler): reintroduce fix from v0.20.1 that got lost

api/deployment/create.go
Taking the injected default duty away from CLI [here](https://github.com/go-vela/cli/blob/010e3166b256e365315ceb91e30bb70403a458f5/command/deployment/add.go#L47). Will be a follow up PR after this.
=> enhance(api/deploy): use default branch if ref is not supplied

api/build/cancel.go
This will prevent stale build_executable items from piling up if users cancel pending builds.
=> fix(api/build): cancel build removes build_executable from table

compiler/native/environment.go, compiler/native/environment_test.go, compiler/native/expand.go
This is the first of three changes that will enhance the `vela exec pipeline` command. These changes fall under the `Server` section below.
`vela exec pipeline` does not work with templates. It also does not work with custom environments if the user is trying to emulate any of the default environment variables, such as `VELA_BUILD_COMMIT`.
1. Execute the local environment sourcing _after_ the default env override. This will ensure that user-set values that would be found in the default environment will be properly interpreted by the compiler.
2. Adjustments to `getTemplate` that allows the compiler to read both from local file tree as well as remote using a GitHub token.
1. Remove calls to merge environment with default environment found in …
=> enhance(compiler): environment and template adjustments for local compilation

compiler/native/compile_test.go, compiler/native/expand.go, compiler/native/parse_test.go, compiler/native/testdata/steps_pipeline.yml, compiler/native/transform.go, compiler/native/transform_test.go, go.mod, go.sum
Depends on: https://github.com/go-vela/types/pull/327
Ref: https://github.com/go-vela/community/issues/435
Note: all the compiler pkg test changes for `AutoCancel` is so the tests can pass. They match what is in [this PR](https://github.com/go-vela/server/pull/911)
=> fix(compiler): return error on bad regular expressions that fail to compile in Purge

api/admin/clean.go, database/executable/clean.go, database/executable/clean_test.go, database/executable/interface.go, database/integration_test.go
As builds tend to get stuck in `pending` or `running` states, the clean endpoint has been great for routine clean up. However, it didn't clear the executable from the DB, which will only sit there forever without  manual intervention before this change.
=> fix(admin/clean): clean executable when build is cleaned

api/build/auto_cancel.go
A missing component of [this fix](https://github.com/go-vela/server/pull/978)
=> fix(api/build): pop executable when pending build is auto canceled

api/scm/sync.go, api/scm/sync_org.go, mock/server/scm.go, mock/server/server.go, router/scm.go
Using `GET` here was a mistake... we should be using `PATCH`.
Breaking for obvious reasons
=> fix(router/scm)!: change HTTP method from GET to PATCH for sync endpoints

api/schedule/create.go
Before:
```json
{
"error": "schedule name must be set"
}{
"error": "unable to create new schedule myvela: empty schedule name provided"
}
```
After:
```json
{
"error": "schedule name must be set"
}
```
UI can't handle the first one and just prints `Status 400`
=> fix(api/schedule): early exit for empty name

api/build/graph.go, api/metrics.go, database/build/build_test.go, database/database.go, database/log/log_test.go, database/pipeline/pipeline_test.go, database/repo/repo_test.go, database/user/user_test.go, internal/token/refresh_test.go, router/middleware/build/build_test.go, router/middleware/claims/claims_test.go, router/middleware/logger.go, router/middleware/org/org_test.go, router/middleware/perm/perm_test.go, router/middleware/pipeline/pipeline_test.go, router/middleware/repo/repo_test.go, router/middleware/service/service_test.go, router/middleware/step/step_test.go, router/middleware/user/user_test.go, router/middleware/worker/worker_test.go, secret/native/count_test.go, secret/native/create_test.go, secret/native/delete_test.go, secret/native/get_test.go, secret/native/list_test.go, secret/native/update_test.go
its not everything, but its some of them
=> chore: fixing code lint issues

compiler/template/starlark/testdata/build/large/want.yml, go.mod, go.sum, scm/github/webhook.go
Follow up to https://github.com/go-vela/types/pull/332
=> fix(scm): process reopened action for pull request event

api/build/graph.go
closes https://github.com/go-vela/community/issues/883
the error returned when complexity is high wasn't properly formatted, so it couldn't be displayed in UI like other errors; you would just end up with a generic internal network error without any other information. this should help signal to the user what is going on better, though maybe the message itself could be tweaked even more?!
=> fix(graph): return proper error on complex builds

.github/workflows/reviewdog.yml
Fixing the timeout errors for the linter
=> fix(ci): add timeout to golangci-lint reviewdog job

compiler/native/expand.go, compiler/native/expand_test.go
A `nil` check that primarily impacts CLI use, as the chances of this happening during normal pipeline expansion within the Vela server is pretty much 0%. 
However, if a user doesn't supply git credentials and tries to validate a pipeline with a remote template, this prevents a seg fault.
=> fix(templates): handle nil PrivateGitHub

compiler/native/compile.go, compiler/native/validate.go, scm/github/webhook.go
Closes https://github.com/go-vela/community/issues/899
I think the real error in the issue is the fact that the pipeline passes validation more so than the repo counter not being updated. By not immediately validating the pipeline after unmarshaling, and rather waiting for the final expansion to validate, we don't need to specify `&& len(step.Template.Name) == 0 `.
This should result in an audit error rather than a build error — thus, no build.
=> fix(compiler): validate yaml.Build post-expansion and fully validate step image

.github/workflows/validate-pr-title.yml
According to our [docs](https://go-vela.github.io/docs/community/contributing_guidelines/#development-workflow), we should accept both formats:
Scope:
- feat(scope): cool thing
No Scope:
- feat: scope-less cool thing
=> fix(ci): title validator handle no parentheses + enforce whitespace

api/repo/list_org.go
closes https://github.com/go-vela/community/issues/853
when GORM is given the proper type, it will use the appropriate query depending on which driver is in use.
tested in local setup with both postgres and sqlite. no functional differences.
as a side note, it's not intuitive to start up the local (or any) stack with sqlite. compilation requires CGO and when using alpine requires you to make sure you are on alpine 3.18 instead of the latest (see issue #1164 on github.com/mattn/go-sqlite3). latest gcc and musl in the newest alpine (3.19.x) apparently do not work with that library. alternatively, and probably preferably, it looks like you can pass `CGO_CFLAGS="-D_LARGEFILE64_SOURCE"` in addition to `CGO_ENABLED=1`.
=> fix(api/list-org-repos): ensure active flag is boolean

api/build/restart.go
fixes https://github.com/go-vela/community/issues/462
i don't believe there are any other fields that need to be reset beyond this.
=> fix(api/build): zero out error on restarted build

scm/github/repo.go, scm/github/repo_test.go, scm/github/testdata/pipeline.star, scm/github/testdata/py.json, scm/github/testdata/star.json, scm/github/testdata/yml_bad_encoding.json
fixes https://github.com/go-vela/community/issues/488
could have been stricter here and disallowed .yml/.yaml for starlark pipelines. what monster would do this? but would be breaking.
also improved testing a bit, including the addition for testing configbackoff properly. though i opted not to test total failure case as that would add ~10s to the test. probably could be done if retries and interval were configurable. maybe that's for another PR.
=> fix(scm): prefer starlark file for starlark pipeline

api/pipeline/compile.go, api/pipeline/expand.go, api/pipeline/validate.go, compiler/engine.go, compiler/native/compile.go, compiler/native/compile_test.go
Context: with the update to the pipeline [validation function](https://github.com/go-vela/server/pull/1036), leveraging `CompileLite(_data, false, false)` with templates present in the pipeline became an impossibility since the resulting pipeline would contain a step without an image. 
Two approaches: revert that enhancement to validation or "fail forward" so to speak and fetch templates if they exist / are replaced locally. 
A downstream benefit of this is the removal of the arguably confusing `--template` boolean flag in the CLI.
I think one could argue that the benefit of an "ignore templates" option is the opportunity to validate pipeline changes without worrying about pulling in templates. I think this is a fair point, but I also think combining [our YAML …
=> fix(compiler): remove template param from CompileLite

api/webhook/post.go
can be confusing since `push` and `tag`, for example, are grouped under "Push" events in the UI and when you have `tag` enabled it says "no push events enabled" when you actually have one of them enabled. plus, it references single events anyway.
=> fix: minor tweak in messaging for event not enabled

compiler/native/compile.go, compiler/native/compile_test.go
[This validation](https://github.com/go-vela/cli/blob/00bbc8f12f9c05365a208a5881d612aea85168e9/action/pipeline/validate.go#L118-L132) fails for replaced nested templates without keeping track of what has been called. Generally good for visibility too I'd say, and it's what we do for normal compilations.
=> fix(compiler): track templates in compileInline so CLI validate command works for nested

.github/renovate.json, cmd/vela-server/main.go
this should help us keep the default clone image up-to-date
=> enhance(ci): keep clone image updated via renovate

secret/vault/vault.go, secret/vault/vault_test.go
Vault was turning our `int64` inputs into `json.Number` outputs, which caused all the type checking to fail and set those values to 0.
Also added a test to confirm existence of fields for library.Secret in api.Secret data
=> fix(vault): fix for integer64 fields

secret/vault/vault.go, secret/vault/vault_test.go
If a vault secret has not been updated since before `v0.23`, it will not have `allow_events` or `allow_substitution`. We can infer these values by converting event slice into the allow events mask and by setting substitution setting to the same setting as the command setting.
I didn't include any update process on the Vela side. Fortunately the UI submits the entire secret form on update, so users will slowly update their vault secrets on their own accord. 
We could also consider creating a migration script of sorts to prevent this code, but we're also supporting v1 and v2 of Vault in code as well. Not saying that's an excuse, but perhaps revisiting our backwards compatibility in general could be a good future issue 🤷
=> fix(vault): parse pre-v0.23 vault secrets

api/worker/create.go
simple typo fix 
v0.23 api-spec.json causes an error in swagger
```
Semantic error at paths./api/v1/workers.post.responses.201.schema.$ref
$ref paths must begin with `#/`
```
=> fix: swagger typo in CreateWorker

.github/workflows/validate-pr-title.yml, api/webhook/post.go, go.mod, go.sum
Applying https://github.com/go-vela/server/pull/1088 to `v0.23.4-patch` for patch release.
=> patch(v0.23.4): apply approve build fix + upgrade types

compiler/native/compile.go, compiler/native/compile_test.go, compiler/native/expand.go, compiler/native/expand_test.go, compiler/native/testdata/long_template.yml
Example pipeline:
`.vela.yml`
```yaml
version: "1"
metadata:
render_inline: true
templates:
- name: example
source: example.yml
type: file
```
`example.yml`
```yaml
metadata:
template: true
stages:
wait:
steps:
- name: run
image: alpine
commands:
- sleep 20
- printenv
test:
needs: [ wait ]
steps:
- name: run
image: alpine
commands:
- echo "Hello World"
```
Due to the fact that the steps and stages get modified to include the template name, this configuration will not work due to `wait` stage being transformed to `example_wait`. With this change, that part can be modified to
`needs: [{{ .VELA_TEMPLATE_NAME }}_wait]`
This is beneficial to developing widely used templates without instructing all adopters to use the same template name.
=> enhance(templates): inject template name as variable

api/pipeline/compile.go, api/pipeline/compile_test.go
Immediate follow up to https://github.com/go-vela/server/pull/1076, as splitting a query value on a comma is very finicky given URL encoding and fortunately Gin and `"github.com/google/go-querystring/query"` (sdk-go) both handle multi key queries as a slice input.
=> fix(api/pipeline): correct type for path query param + add testing

compiler/native/compile_test.go, compiler/registry/github/github.go, compiler/registry/github/github_test.go, compiler/registry/github/template.go, go.mod, go.sum, scm/github/access.go, scm/github/authentication.go, scm/github/changeset.go, scm/github/deployment.go, scm/github/github.go, scm/github/github_test.go, scm/github/repo.go, scm/github/webhook.go
Closes https://github.com/go-vela/server/pull/1099, which needs manual intervention due to the hook config breaking change.
=> chore(deps): upgrade go-github to v61

api/repo/create.go, api/types/events.go, api/types/events_test.go, database/repo/repo_test.go
Repo.Events was still using the `go-vela/types/library/actions` package.
=> fix(types): correct actions pkg for repo events

api/build/compile_publish.go, api/webhook/post.go
fixes a nil panic when you supply an invalid worker route, introduced in https://github.com/go-vela/server/pull/1063
=> fix: handle errors from CompileAndPublish

api/types/user.go, api/types/user_test.go, database/integration_test.go, database/repo/count_user_test.go, database/repo/get_org_test.go, database/repo/get_test.go, database/repo/list_org_test.go, database/repo/list_test.go, database/repo/list_user_test.go, database/repo/repo.go, database/repo/repo_test.go, router/middleware/repo/repo_test.go
Even though we have the JSON tag of `-` to prevent marshaling of token / refresh token, we may want to further censor information.
This `Sanitize()` function is actually never used, so I slapped it on the `ToAPI()` call for repo owners and extended it to exclude `favorites` and `admin` because not only can favorites get huge, they also shouldn't really be public info.
=> fix(repo): sanitize owner information

router/middleware/logger.go
log user name to field designated for such (see https://www.elastic.co/guide/en/ecs/current/ecs-user.html)
=> enhance(log/ecs): log user to user designated field

constants/limit.go, database/types/dashboard.go, database/types/dashboard_test.go, database/types/user.go, database/types/user_test.go
Add some sense to the code base
=> fix(dashboards): add limit to repos for dashboards and dashboards for users

mock/server/dashboard.go, mock/server/dashboard_test.go, mock/server/server.go
=> enhance(mock): add dashboard responses from server in mock

api/dashboard/get.go, api/types/dashboard.go
If someone disables a repo that is attached to a dashboard, the UI can interpret the active status to display a message of some kind.
=> fix(dashboards): add active status on repo partial

mock/server/dashboard.go
=> fix(mock): correct type for mock response

compiler/native/expand.go, compiler/native/expand_test.go
Fixed this for [compile inline](https://github.com/go-vela/server/pull/1067) but not in normal CompileLite, which causes `vela validate` to fail on nested templates locally replaced with the error:
```sh
FATA[0000] local template with name foo not included in pipeline templates
```
Now the resulting pipeline will include all templates called and pass that validation.
=> fix(compiler): aggregate templates for nested pipelines

api/admin/worker.go
Noticed in the [admin router](https://github.com/go-vela/server/blob/v0.23.4/router/admin.go#L61) that this endpoint is wired up  under `[...]/workers/:worker/register` but it's currently documented as `[...]/workers/:worker/register-token`
=> chore: Correct the register worker token swagger path

api/build/id_request_token.go
commands=false in the sdk is actually not applying the query param at all. makes sense, but my bad on the strict validation.
fixes this worker error when using `id_request: write`
```
error:unable to parse 'commands' query parameter as boolean : strconv.ParseBool: parsing "": invalid syntax
```
=> fix: only convert commands query param when provided

go.mod, go.sum, queue/redis/length_test.go, queue/redis/pop_test.go
closes https://github.com/go-vela/server/security/dependabot/17 although only used (accidentally?) in tests in our case. we do still have an indirect dependency on the good version of the library.
=> fix(deps): switch go-jose lib

.golangci.yml, api/auth/validate_oauth.go
one overlooked swagger annotation issue
fix for golangci-lint config (`format` is not a valid property - see https://golangci-lint.run/usage/configuration/#output-configuration) - which also fixes error reporting locally in certain editors
=> fix: swagger error and golangci-lint config

scm/github/repo.go
deprecated since https://github.com/google/go-github/releases/tag/v57.0.0
=> fix(scm): avoid usage of deprecated method in github module

scm/github/repo.go
this was modified in the UI with the refactor but not updated for sending step specific commit statuses to the SCM. "Details" links shown in the GitHub UI will still bring you to the right build, it just won't auto-expand any targeted step.
old format: `<domain>/org/repo/1#step:3`
new format: `<domain>/org/repo/1#3`
=> fix: use correct build links to steps for commit status updates

api/oi_config.go, api/types/oidc.go
I spent some time over this weekend experimenting with the new OIDC feature and noticed that the `/_services/token/.well-known/openid-configuration` endpoint doesn't align with AWS's expected format for openid. AWS's documentation specifies the required fields, which you can find at https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html#manage-oidc-provider-prerequisites. After updating the API response to include all of these fields, the issue was resolved. 
openid documents the discovery endpoint schema within https://openid.net/specs/openid-connect-discovery-1_0.html.
=> fix(oidc): add expected fields

internal/token/generate_rsa.go, internal/token/mint.go
These two situations should probably be logged.
=> enhance(token): add info logging on created private key, debug for minted ID token

api/webhook/post.go
`r` is what we get from parsing SCM webhook; `repo` is what we have in the database. Need the latter to gather proper credentials for contributor call.
=> fix(webhook): use correct repo variable to populate client credentials

queue/redis/ping.go, queue/redis/redis.go
when workers cant ping the queue the log/context we get back is missing everything useful.
=> enhance: surface redis ping errors

database/types/repo.go
note: we don't actually return an error, we just log it, but it adds a bit of unnecessary noise.
=> fix(db/types): add check before owner decrypt

api/types/string.go, compiler/native/compile.go, compiler/native/compile_test.go, compiler/native/expand_test.go, compiler/native/parse.go, compiler/native/parse_test.go, compiler/native/substitute.go, compiler/template/native/convert.go, compiler/template/native/render.go, compiler/template/native/render_test.go, compiler/template/starlark/render.go, compiler/template/starlark/render_test.go, go.mod, go.sum, mock/server/pipeline.go
Follow up from https://github.com/go-vela/types/pull/386
And also fixing the tests that were broken from https://github.com/go-vela/types/pull/387
=> fix: upgrade yaml library to go-yaml v3 over buildkite

api/webhook/post.go, scm/github/repo.go
This will greatly ease the amount of sleuthing users have to do when they don't see a Vela status show up on their PR / commit. 
Further, the context URL will point to the hooks page, which should take users right to the error message.
=> enhance: add a status call for failed compilation

api/webhook/post.go
fixes a regression introduced in #1175 where `retryLimit - 1` duplicate hooks are created after success.
cc @jbrockopp
=> fix: exit hook retry loop on success

api/dashboard/list_user.go
when there are no dashboards we currently return 'null'. this change will return an empty list instead
=> fix(api/dashboards): return empty list

api/dashboard/list_user.go
scenario: another user adds dashboard, you add that dashboard to your list, other user decides to delete dashboard. the dashboard remains in your list but is inaccessible. we have the id, but not the name (because it has been deleted). this will set the name to "(not found)" in the response returned to the callee. we can utilize this in the UI(s) to provide appropriate messaging for users to update their dashboard list.
=> fix(dashboards): set name for deleted dashboard

compiler/native/compile_test.go, compiler/native/parse.go, compiler/native/parse_test.go, compiler/native/testdata/golang_inline_stages_env.yml, compiler/native/testdata/inline_with_stages_env.yml
when referencing a template that defines a global environment, but the base pipeline doesn't, `pipeline.Environment` will be `nil` as its zero value. when the template is parsed and attempting to [set the global environment](https://github.com/go-vela/server/blob/9bb4acca095dc88f92c48dd45f9bdd587740115b/compiler/native/compile.go#L256) we currently cause a `assignment to entry in nil map` error. this fix initializes an empty environment.
test case:
`.vela.yml`:
```yaml
version: "1"
metadata:
render_inline: true
templates:
- name: nil-panic
source: .nil-panic.yml
format: go
type: file
vars:
foo: bar
```
`.nil-panic.yml`:
```yaml
metadata:
template: true
environment:
foo: "bar"
stages:
vendor:
steps:
- name: test
image: alpine
commands:
- echo hello
```
workaround is to define `environment: …
=> fix(templates): prevent nil panic

compiler/native/compile.go
Giving metadata default empty values when nil causes [this environment section](https://github.com/go-vela/server/blob/79667fd483f21daeb8366b09d1927bca507139f4/compiler/native/environment.go#L310-L323) to set values it shouldn't set, resulting in the worker not supplying its own defaults. This causes local exec to not properly mount the workspace.
=> fix(compiler): add instance only when metadata is not nil

internal/token/mint.go, internal/token/mint_test.go
tiny fix for https://github.com/go-vela/server/pull/1172 `invalid reference format` with sha tags
or should we use `reference.Parse` similar to the [worker code](https://github.com/go-vela/worker/blob/main/internal/image/image.go#L61-L75)
=> fix(oidc): image parse sha support

internal/token/mint.go, internal/token/mint_test.go
Applying https://github.com/go-vela/server/pull/1207
=> fix(patch): apply image parse fix to v0.25.2 patch

compiler/native/compile.go, compiler/native/expand.go, compiler/native/expand_test.go, compiler/native/native.go, compiler/native/native_test.go
This is a fairly uncommon issue, but whenever folks are looking to use a template multiple times in one build, Vela will fetch that template each time. With this in-memory cache on the compiler object, we can avoid unnecessary calls to the SCM.
=> enhance(compiler): cache templates per compilation

api/webhook/post.go
=> fix(webhook): use correct repo variable for enqueue

api/pipeline/template.go, api/types/pipeline.go, api/types/pipeline_test.go, compiler/engine.go, compiler/native/compile.go, compiler/native/expand.go, compiler/native/parse.go, compiler/native/parse_test.go, compiler/template/native/render.go, compiler/template/native/render_test.go, compiler/template/starlark/render.go, compiler/template/starlark/render_test.go, constants/limit.go, database/integration_test.go, database/pipeline/create_test.go, database/pipeline/table.go, database/pipeline/update_test.go, database/testutils/api_resources.go, database/types/pipeline.go, database/types/pipeline_test.go, internal/yaml.go, internal/yaml_test.go, mock/server/pipeline.go, router/middleware/pipeline/pipeline_test.go
Added `warnings` field to pipelines that will aggregate non-breaking but call-out worthy YAML transgressions.
=> feat(pipeline)!: add warnings to pipelines that use legacy YAML lib or have dupl anchors in map

api/build/status.go, api/repo/status.go, api/types/build.go, api/types/repo.go, router/router.go
implements https://github.com/go-vela/community/issues/749 in a way that doesnt impact current status svg responses.
instead, two new endpoints to get unauthenticated access to "lite" versions of repo and builds.
- potential impact to the database from unauthenticated and untrackable spam. but... this is not a new problem. could easily do it elsewhere (dashboards, pat auth, etc) if you were determined, but still.
- the `/badge` endpoint for "private repos" have never been protected, but this is obviously opening the door much wider.
=> feat: status endpoints

api/deployment/create.go, api/deployment/get_config.go, compiler/types/pipeline/deployment.go
Give a response on an invalid deployment on creation rather than letting the webhook handler deal with it all the time.
=> enhance(deploy): validate on CreateDeployment

api/metrics.go, queue/redis/route_length.go, queue/redis/route_length_test.go, queue/service.go
Helpful info for installations with multiple queue routes
=> enhance(metrics): include route specific queue length

api/build/restart.go
Copy paste error when using `Enqueue` for restart.
Source: https://github.com/go-vela/server/pull/1227
=> fix(build): use item build host

api/build/compile_publish.go, api/pagination.go, api/webhook/post.go, database/build/count_repo.go, database/build/count_repo_test.go, database/build/interface.go, database/build/list_repo.go, database/build/list_repo_test.go, database/integration_test.go
for listing builds, the previous implementation did a count, but always returned the total count while excluding after/before query params (but honoring other filters, if present). this resulted in incorrect header links. the header links pointing at subsequent pages also didn't honor existing query params, so if you followed the links you could end up with different results.
=> fix(build): ensure count/pagination links account for filter/query params

internal/yaml.go, internal/yaml_test.go
i feel like this can even be better, so if you have any improvements, let me know. referencing go-yaml likely doesn't mean much to the average user.
perhaps there is a place somewhere that lists known incompatibilities that we can refer to in the message?
=> fix(yaml): improved messaging

api/log/update_service.go, api/log/update_step.go
undo marking log update endpoints as deprecated. they are very much in use.
other endpoints marked as deprecated are creating step/service logs (POST requests). i believe those are truly deprecated and probably up for removal.
=> fix(api/docs): undo deprecation

compiler/native/native.go
When we don't set this to an empty map, it'll use old sources of templates
=> fix(compiler): bust template cache on Duplicate

compiler/types/pipeline/deployment.go, compiler/types/pipeline/deployment_test.go
Given the following deployment config:
```yaml
deployment:
parameters:
region:
description: cluster region to deploy
required: true
type: string
options:
- us-west-1
- us-south-2
cluster_count:
description: number of clusters to deploy to
required: false
type: integer
max: 10
```
A deployment triggered via CLI like this:
```sh
vela add deployment  --target here --parameter "region=us-west-1" --parameter "CLUSTER_COUNT=50"
```
Would pass validation, even though the parameter is injected as `DEPLOYMENT_PARAMETER_CLUSTER_COUNT` regardless of the casing when it's passed in.
=> fix(deployment): validate inputs in a case-insensitive manner

compiler/types/yaml/yaml/ruleset.go, compiler/types/yaml/yaml/ruleset_test.go, compiler/types/yaml/yaml/testdata/ruleset_collide.yml, compiler/types/yaml/yaml/testdata/ruleset_collide_adv.yml, compiler/types/yaml/yaml/testdata/ruleset_unknown_field.yml
It looks like these two unchecked `unmarshal` calls were part of the [initial go-vela/types commit](https://github.com/go-vela/types/blame/main/yaml/ruleset.go), so I am not sure if there is some extra backstory here that I'm missing. However, it would be nice to bubble up errors here, since suppressing them just returns an empty rules block which gets converted to no rules.
```yaml
ruleset:
branch:
event: push
branch: main
```
converts to -->
Before:
```yaml
ruleset:
operator: and
matcher: filepath
```
After:
```
error: "mapping key \"branch\" already defined"
```
FWIW, the unmarshaler is not strict on fields, so this won't break pipelines that are using unknown fields (threw in a test just to confirm).
=> fix(yaml): bubble up rules struct unmarshal errors

compiler/native/compile_test.go, compiler/native/native_test.go, compiler/registry/github/github.go, compiler/registry/github/github_test.go, compiler/registry/github/template.go, go.mod, go.sum, router/middleware/compiler_test.go, scm/github/access.go, scm/github/app_permissions.go, scm/github/app_permissions_test.go, scm/github/app_transport.go, scm/github/authentication.go, scm/github/changeset.go, scm/github/deployment.go, scm/github/github.go, scm/github/github_client.go, scm/github/github_client_test.go, scm/github/github_test.go, scm/github/repo.go, scm/github/repo_test.go, scm/github/webhook.go
Because `go-github` changed the way `New` operates under the hood, we can no longer compare something like 
```go
a := github.New(...)
b := github.New(...)
reflect.DeepEqual(a,b)
```
So I had to tweak some tests to be less strict on this checking. I would have liked to use `cmp` throughout, but there are a lot of unexported fields in our compiler, and it would've been pretty cumbersome to write that test.
=> chore(deps): upgrade go-github to v69

cmd/vela-server/main.go, cmd/vela-server/metadata.go, compiler/types/pipeline/container_test.go, internal/metadata.go, router/middleware/header.go, router/middleware/header_test.go
this "fix" adds support for alternative browser client implementations
use `VELA_CORS_ALLOW_ORIGINS="https://vela-frontend-module.com,https://other-platform-frontend-module.com"` to set an optional list of CORS allowed origins 
the code still defaults to `m.Vela.WebAddress` so current configurations of `VELA_WEB_ADDRESS` are not impacted
=> fix: support list of cors origins

compiler/native/validate.go, compiler/native/validate_test.go, compiler/types/yaml/yaml/ruleset.go, compiler/types/yaml/yaml/ruleset_test.go, compiler/types/yaml/yaml/testdata/ruleset_collide.yml, compiler/types/yaml/yaml/testdata/ruleset_collide_adv.yml, compiler/types/yaml/yaml/testdata/ruleset_unknown_field.yml
These fixes look to be causing some unexpected issues.
=> fix(revert): reverting a couple of 0.26.2 fixes

router/middleware/pipeline/pipeline.go
this was accidentally removed in https://github.com/go-vela/server/pull/1111
=> fix(api/pipeline): use WithUser on middleware compile

scm/github/opts.go, scm/github/opts_test.go, scm/github/repo.go
If an installation wants to support a different webhook address for a pass through to the Vela server, the suffix of `/webhook` should not be forced onto those custom addresses
Marking as breaking because users could have already accounted for this by supplying a custom address knowing it ends in `/webhook`
=> enhance(scm)!: support truly custom webhook address

go.mod, go.sum
for some reason, dependabot doesn't like our go.mod formatting, so our validate step is failing. recreated the dependabot PRs (https://github.com/go-vela/server/pull/1283, https://github.com/go-vela/server/pull/1282) in this one.
=> chore(deps): update go-jose and x/net

database/integration_test.go, database/jwk/create.go, database/jwk/create_test.go, database/jwk/get.go, database/jwk/get_test.go, database/jwk/interface.go, database/jwk/list.go, database/jwk/list_test.go, database/jwk/rotate_test.go, database/testutils/api_resources.go, database/testutils/mock_args.go, database/types/jwk.go, database/types/jwk_test.go, go.mod, go.sum, internal/token/generate_rsa.go, mock/server/authentication.go
A few breaking changes to function naming / returns and what not from the v2->v3 change. Addressing those in this PR
=> chore(deps): update jwx library to v3

queue/flags.go, queue/flags_test.go
We validate the presence of the public key in `setup.go` because the worker fetches the queue public key. It's not a flag for the worker.
=> fix(queue): remove validation of public key from flag set

compiler/native/expand.go, compiler/native/native.go
Checking for the presence of `"github.com"` in the source config for fetching templates does not mean that the template is public.
By setting `UsePrivateGithub` to `true` when the `WithPrivateGitHub()` function is called, we can add some extra logic to make sure we aren't invoking `c.GitHub.Template` when we should be using `c.PrivateGitHub.Template`
=> fix(compiler): allow for private github.com templates

api/admin/settings.go, api/dashboard/create.go, api/types/settings/platform.go, api/types/settings/platform_test.go, cmd/vela-server/flags.go, constants/limit.go, database/settings/create_test.go, database/settings/get_test.go, database/settings/table.go, database/settings/update_test.go, database/types/dashboard.go, database/types/dashboard_test.go, database/types/settings.go, database/types/settings_test.go, mock/server/settings.go, scm/github/access.go
Since the dashboard repos are just stored as JSON in the database, the limit on number of repos should probably be adjustable rather than firmly set at 10.
Breaking because it adds a column to the settings DB table.
=> enhance(settings)!: make dashboard repo limit adjustable by platform admins

scm/github/repo.go
This will properly set visibility to Vela public if it has a combination of `private: true` and `visibility: internal`
=> enhance(github): use visibility field if present in toAPIRepo func

api/log/create_service.go, api/log/create_step.go, api/service/plan.go, api/step/plan.go, api/types/log.go, api/types/log_test.go, database/integration_test.go, database/log/count_build_test.go, database/log/count_test.go, database/log/create_test.go, database/log/delete_test.go, database/log/get_service_test.go, database/log/get_step_test.go, database/log/get_test.go, database/log/list_build_test.go, database/log/list_test.go, database/log/table.go, database/log/update_test.go, database/types/log.go, database/types/log_test.go, mock/server/log.go
adding timestamp field to log table.
to note, `BIGINT` used for consistency with other tables, but might not be the most straight-forward for partitioning by time spans. open to change that or add on to it.
=> enhance(log)!: add timestamp field

api/build/restart.go, api/webhook/post.go
Technically this change is only needed for restart since `build` is up to date with its number and such in `PostWebhook` but I think using `item.Build` for all post- compiling/planning is good practice.
=> fix(api): pass correct build into Gatekeep helper func

scm/github/webhook.go, scm/github/webhook_test.go
Because of the fallthrough [here](https://github.com/go-vela/server/blob/ec2dca5e078ba3539ece90c7b07e47b90282ecb7/api/webhook/post.go#L686), the repo gets some fields updated [here](https://github.com/go-vela/server/blob/ec2dca5e078ba3539ece90c7b07e47b90282ecb7/api/webhook/post.go#L712-L726), so we should make sure all those fields are up to date.
=> fix(scm): set all repo info in custom props handler

.github/workflows/test.yml
didn't realize this field was updated and missed the annotation on the `test` run (see https://github.com/codecov/codecov-action?tab=readme-ov-file#arguments for field info on `files`)
=> fix(ci): file -> files in codecov action field

internal/token/mint.go
Should this be marked breaking and put in `v0.28` or slotted into `v0.27` as part of a patch?
=> fix(oidc): no trailing colon on non-action events in claim
